### ISSUE TITLE
Show Currently Active day indicator

### ISSUE THREAD

**Issue by dineshdevkota001** [hoangnm/react-native-week-view#104]
Thanks for a great library. I ran through the documentation but couldnt find a way to highlight current day header. Did i miss something?
Thank you,

**Comment by pdpino** [comment]
Currently, there is no way to highlight today in the header. You can use the `showNowLine` prop to display a line in the hour and current day (but it shows on the grid, not on the header).

I think we can add a prop to allow special styling for today in the header. @dineshdevkota001 any suggestions on how the highlight should look?

**Comment by dineshdevkota001** [comment]
Not so much, an Indicator for the current date works. or we can just highlight it in a rounded box.
