### ISSUE TITLE
Custom Render Method

### ISSUE THREAD

**Issue by dandresfg** [hoangnm/react-native-week-view#107]
The possibility to create a custom component for events.

The library needs to provide a way to customize at 100% the render method, can provide the coordinates by props, or apply them in a simple father view of every event... To be sure they cannot modify them.

Good library, ill use it soon.

**Comment by pdpino** [comment]
Hi @dandresfg , thanks for the suggestion!

Could you provide more details on what you want to achieve? You want to customize the render method for the event component? or for other part? It would be useful if you could provide an screenshot, or a concrete example of your use case.

The events can already be customized with the [`EventComponent` prop](https://github.com/hoangnm/react-native-week-view#custom-eventcomponent). You can fully customize what is rendered inside an event. Is this what you need?

**Comment by dandresfg** [comment]
Yep, that's exactly. Kinda blind by myself.
