### ISSUE TITLE
Moving between dates changing the numberOfDays make miss some pages.

### ISSUE THREAD

**Issue by dandresfg** [hoangnm/react-native-week-view#118]
Me again, hello.

So, the context is this: Ive been working with 3 as **numerOfDays**, and all is great...
but when i changed it to 1... and come back to the pages previous loaded the week view jumped between 3 days again and not 1.

[You can see what im doing here](https://imgur.com/a/eBN2Ybi)

____ June 30 ____
SwipeNext (1 day) (from here all the events were load with 1 as numberOfDays and it works good)
SwipePrev (3 days) (Dates between now and June 30 were load with 3 as numberOfDays and it doesnt work as expected)

**Comment by pdpino** [comment]
Thanks for the bug report. I have seen this too

For the moment, the only workaround is not changing the `numberOfDays` prop, but obviously this is not ideal.

I will try to fix this bug soon

**Comment by dandresfg** [comment]
```javascript
  componentDidUpdate(prevprops) {
    if (this.props.locale !== prevprops.locale) {
      setLocale(this.props.locale);
    }

    // Detect change
    if(this.props.numberOfDays !== prevprops.numberOfDays){
      const initialDates = this.calculatePagesDates(
        prevprops.selectedDate,
        this.props.numberOfDays,
        prevprops.prependMostRecent,
      );
      //
      this.setState({ initialDates })
    }
  }
```

Try with this, works for me (i will test it deeply)

**Comment by pdpino** [comment]
Thanks for the suggestion. I used something similar to that, uploaded to [this hotfix branch](https://github.com/pdpino/react-native-week-view/tree/hotfix/change-n-days) for now.

I have to test it further, and I'm thinking of a more optimal solution

**Comment by dandresfg** [comment]
maybe instead of use calculatePagesDates... You can use another method and read the items, and add the dates missing. (IDK how to do this but i think...)

```
if( (date[0] + 1) is not the day after date[1] ){
   arr.push( date[0] + 1 ) // I mean, moment can check this (i saw long time ago)
} 
```

**Comment by rdewolff** [comment]
I have the same issue, whatever the `numberOfDays` value is, the jump is always 7 days.

**Comment by rdewolff** [comment]
Any workaround or plan to fix this?

**Comment by dandresfg** [comment]
You can use my solution...

Change this (WeekView.js)
```javascript
  componentDidUpdate(prevprops) {
    if (this.props.locale !== prevprops.locale) {
      setLocale(this.props.locale);
    }
  }
```

to this
```javascript
  componentDidUpdate(prevprops) {
    if (this.props.locale !== prevprops.locale) {
      setLocale(this.props.locale);
    }

    // Detect change
    if(this.props.numberOfDays !== prevprops.numberOfDays){
      const initialDates = this.calculatePagesDates(
        prevprops.selectedDate,
        this.props.numberOfDays,
        prevprops.prependMostRecent,
      );
      //
      this.setState({ initialDates })
    }
  }
```

it will erase al the loaded pages, and reload new ones... Works for me... check it out.

**Comment by pdpino** [comment]
> Any workaround or plan to fix this?

Yes @rdewolff,  I plan to fix this bug soon, but I've been very busy. It has top priority as it is an important bug.

Current workarounds:
* Keep `numberOfDays` fixed (you _should_ not see this bug if `numberOfDays` does not change)
* Use [this hotfix branch](https://github.com/pdpino/react-native-week-view/tree/hotfix/change-n-days) from my fork, which has a similar fix as the one given by dandresfg. ([this commit](https://github.com/pdpino/react-native-week-view/commit/0ede74199443dddd4e2fb8c3a601fb90feede4ed) has the change, in case you want to see it).
  Is just a hotfix for the moment so it won't be merged to master, I'm working on a better solution to submit a PR

**Comment by rdewolff** [comment]
Thanks, I’ll give this solution a try. 

Would love to see a fix in the master branch 🙏🤩

**Comment by pdpino** [comment]
Update: we decided to apply the hotfix to the master branch, so the bug should be fixed now. We will try to apply a more efficient solution in the future
