### ISSUE TITLE
How to show FirstDay of the Week Sunday and LastDay of the Week Saturday. Currently its showing firstDay Of the Week Monday and Last is Sunday.

### ISSUE THREAD

**Issue by AbhishekMuknak** [hoangnm/react-native-week-view#119]
In header threre are day name and days are listed starting from monday to sunday. but i want the start day sunday and end day saturday. because i am getting data from api when i pass week no . in javascript week start from sunday and ends on saturday. In your component start day is monday and end date is sunday. because of that i am unable to show the event on sundays.  i there any props so i can show start day as sunday and end day as saturday.

**Comment by pdpino** [comment]
> i there any props so i can show start day as sunday and end day as saturday.

For the moment, there is no prop to do this. I think we can add this soon

**Comment by AbhishekMuknak** [comment]
Thanks Sir
