### ISSUE TITLE
Add PinchGestureHandler

### ISSUE THREAD

**Issue by rdewolff** [hoangnm/react-native-week-view#130]
It would be great to have an option to set PinchGestureHandler. For example we could set the amount of day(s) displayed using this event handler.

**Comment by pdpino** [comment]
Thanks @rdewolff ! This would be really nice. I have also thought of this for the amount of hours vertically

We can definitely try to do this, but I'm not sure how smooth will the animation be (i.e. we may need some efficiency improvements)

**Comment by rdewolff** [comment]
Only way to know is to test 😎
Vertical pinch would change the amount of hours displayed, and horizontal pinch would change amount of days displayed.

**Comment by pdpino** [comment]
First (very early) version for the vertical pinch:

https://user-images.githubusercontent.com/20805451/181384685-dd884e90-2853-4cc8-b038-ca1bd7311e63.mp4

**Comment by rdewolff** [comment]
Ah that's great. I had always thought this would be a nice addition to the lib.

**Comment by harshil-daynil** [comment]
@pdpino @rdewolff adding pinch gestures anytime soon?

**Comment by harshilJs** [comment]
@pdpino @rdewolff releasing pinch gestures anytime soon? is there any branch or fork I can try?

**Comment by shawarmaz** [comment]
Looking forward to this as well

**Comment by pdpino** [comment]
I implemented the vertical pinch:

![2023-05-13-pinch-vertical-frame](https://github.com/hoangnm/react-native-week-view/assets/20805451/bf3cc958-d9c3-4430-9350-8cd1043783c8)

The UI is a bit laggy, we can fix that later.

I will send a PR as soon as we resolve #306. In the meantime check [this branch](https://github.com/pdpino/react-native-week-view/tree/feature/preview/130-pinch-vertical)
