### ISSUE TITLE
Bug when switching `hoursInDisplay`

### ISSUE THREAD

**Issue by rdewolff** [hoangnm/react-native-week-view#131]
As a user, when I switch the `hoursInDisplay` value on the fly, the hours gets messed up in the margin.

Demo of changing `hoursInDisplay` prop value with events displayed at wrong time:

https://user-images.githubusercontent.com/130704/131263490-f5f59bf2-2849-4787-89ec-f98e301d749e.mp4

**Comment by pdpino** [comment]
Thanks for reporting this. I will try to fix it ASAP

I think I found the culprit in the code, but I'm very busy right now so I'm not sure when can I implement it and send a PR.

**Comment by pdpino** [comment]
I fixed this bug and sent a PR. Here is a gif of the result:

![bug-change-hours-in-display](https://user-images.githubusercontent.com/20805451/132554449-552cb4f0-7939-4e1b-8860-fdb7cf21c9de.gif)

The NowLine updates its position smoothly, but the events not so smoothly. We can improve this in the future :slightly_smiling_face:
