### ISSUE TITLE
Add ability to use custom component for day header

### ISSUE THREAD

**Issue by rdewolff** [hoangnm/react-native-week-view#134]
it would be great to be able to specify the custom component for the day header.

The overload method would receive the date as a param and render a component in the allocated space, as shown in the following screenshot.

![iPhone_12](https://user-images.githubusercontent.com/130704/132710917-120f8b27-4035-407b-9450-76d93e4f0e7f.png)

**Comment by pdpino** [comment]
Have you tried customizing the props `headerStyle`, `headerTextStyle`, `dateFormatHeader` and/or `TodayHeaderComponent` for your use case?

**Comment by rdewolff** [comment]
Yeah I have checked. Maybe I have missed someting, but my use case is the following:

As a user, I want to be able to see the total number of meetings I have during the day in the day header.

And I think this is currently not possible.

**Comment by pdpino** [comment]
Thanks for the answer, that cannot be done at the moment.

A couple more observations:
* If this custom component is provided, all the other header-related props mentioned will be ignored (which is fine)
* The custom component could also receive a prop `isToday`, so the developer does not have to check this manually
