### ISSUE TITLE
Timetable pushing start date by 1 hour

### ISSUE THREAD

**Issue by JoeKlimcak** [hoangnm/react-native-week-view#135]
Apologies if I'm missing something obvious. Returned back to months-old code that used to work without any issues. Now, during testing, I've noticed each event is being pushed by 1 hour into the future. Example list of events being passed in:

```
[
    {
        "description": "GRECO",
        "color": "#023a75", 
        "endDate": 2021-09-20T14:30:00.000Z, 
        "id": "gr_2021_09_20_13_00", 
        "startDate": 2021-09-20T13:00:00.000Z
    },
    {
        "description": "FREESTYLE",
        "color": "#F3C345", 
        "endDate": 2021-09-20T16:30:00.000Z, 
        "id": "fr_2021_09_20_15_00", 
        "startDate": 2021-09-20T15:00:00.000Z
    }
]
```

Result in the timetable:

![Screenshot 2021-09-20 at 06 23 13](https://user-images.githubusercontent.com/19940004/133959880-bbddc66d-1131-466c-8b11-e7094a7e866e.png)

**Comment by pdpino** [comment]
I think this could be due to a timezone discrepancy, unless you are working from a UTC timezone.
Could you please try logging/printing this for each date of your events (`startDate` and `endDate`):

```
date.toString() // local date (in your timezone)
date.toUTCString() // UTC date (in GMT 0)
```

This library works with local datetimes (i.e. with respect to your local timezone), so it should match the value given by the `toString()` methods

**Comment by JoeKlimcak** [comment]
You're right, that's where the discrepancy comes from. Your prints show:
```
 LOG  Tue Sep 21 2021 14:00:00 GMT+0100 (BST)
 LOG  Tue, 21 Sep 2021 13:00:00 GMT
```
That being said, still confused about why this is happening. The dates are first received as a string, and then converted to a date object with `startDate = new Date(date_string)`. At this point, the time is still correct, and as far as I understand, JavaScript's Date object already takes into account localization. But from the looks of it, react-native-week-view thinks it's UTC and thus localizes again?

We already receive the datetimes from upstream in the correct timezone (GMT+1), we just need that to be passed on to the UI.

**Comment by pdpino** [comment]
Hmm, could you please show a complete example with: `date_string` received, the parsed `date` printed with `toString()` and `toUTCString()`, and say what is the expected value in the UI (e.g. you expect it to show as 13hrs)?

This library uses momentjs underneath to handle dates, so mostly we do stuff like `moment(event.startDate).hours()` (i.e. we don't change the timezones manually :grin:). Although there could be some native-date or momentjs-date timezone discrepancy :thinking:

**Comment by JoeKlimcak** [comment]
Nope, I was wrong. What's happening is that JavaScript by default assumes the date that arrived is UTC. Then it picks up my localisation and adds the offset. What I haven't figured out yet is why this only became a problem for us now, but that's nothing to do with you. Thanks for the help!

**Comment by pdpino** [comment]
I see. Good luck!
Thanks for using the library
