### ISSUE TITLE
How to change Grid line color based on theme?

### ISSUE THREAD

**Issue by saravanakumargn** [hoangnm/react-native-week-view#138]
Is any way to change the Grid border (line) color? I would like to change based on my theme (Light or dark)

This should be optional. https://github.com/hoangnm/react-native-week-view/blob/master/src/Events/Events.styles.js#L4
```
const GREY_COLOR = '#E9EDF0';
```

**Comment by rdewolff** [comment]
This is currently not possible

**Comment by pdpino** [comment]
To change the grid colors provide the props:
```js
gridRowStyle={{ borderColor: <color> }}
gridColumnStyle={{ borderColor: <color> }}
```
