### ISSUE TITLE
Add business hours

### ISSUE THREAD

**Issue by sadez** [hoangnm/react-native-week-view#140]
I think it will be a good feature to have, I was thinking of a props like [fullcalendar](https://fullcalendar.io/docs/businessHours) : 

```
businessHours: [ // specify an array instead
  {
    daysOfWeek: [ 1, 2, 3 ], // Monday, Tuesday, Wednesday
    startTime: '08:00', // 8am
    endTime: '18:00' // 6pm
  },
  {
    daysOfWeek: [ 4, 5 ], // Thursday, Friday
    startTime: '10:00', // 10am
    endTime: '16:00' // 4pm
  }
]
```

In the current version, the only way I found to do that is to add holidays or week-ends (hours outside business hours) as events and add some grey style and make them unclickable.
![image](https://user-images.githubusercontent.com/8754816/136089164-a058ada2-a07d-4b5f-b4ae-eff3a3f0897d.png)

**Comment by rdewolff** [comment]
Yeah so you can define your "available" or "not available" time.
Something à la SavvyCal https://savvycal.com

**Comment by pdpino** [comment]
This is somewhat similar to #92.

What else would the non-business hours need? Other than being non-pressable and from a different color.
Or the business hours?

**Comment by sadez** [comment]
> This is somewhat similar to #92.
> 
> What else would the non-business hours need? Other than being non-pressable and from a different color. Or what would the business hours need?

Pressable or non-pressable should be optional I think, the only thing essential is making non-business hours with grey as color or different color (it can have events)

**Comment by pdpino** [comment]
Thanks for the answer. Indeed this is very similar to the timeslot use-case, something like changing the background style of the grid without affecting the events too much.

For now, I would kindly suggest you to keep using the current workaround that you mentioned, i.e. using dummy grey events. I do not see a clear way to implement this soon, and there are other features that have precedence. In the long-term we could definitely add this, good to know there are more use-cases for this!

In any case, we are open to suggestions or more ideas into more requeriments of this, how to tackle this, etc (or PRs :slightly_smiling_face:)

**Comment by rdewolff** [comment]
Any update on this one?

**Comment by pdpino** [comment]
Update: check [this comment](https://github.com/hoangnm/react-native-week-view/issues/92#issuecomment-1440956525) with a solution to a similar problem.

Feel free to reopen the issue if needed

**Comment by rdewolff** [comment]
Yeah this is amazing, thanks for the update @pdpino
