### ISSUE TITLE
I want to show overlapping event if there are more than one event on same time and no of event inside the event

### ISSUE THREAD

**Issue by AbhishekMuknak** [hoangnm/react-native-week-view#147]
if there are more than one event on same time then i want to show that event overlapping not side by side. it is showing side by side in following design which makes events width smaller if multiple events on same time period.

**Comment by pdpino** [comment]
This cannot be done for the moment, but we can try to add this at some point.

To clarify, how would the overlapping look? one event smaller than the other? could show an example?

**Comment by AbhishekMuknak** [comment]
If I have 2 jobs scheduled at the same time, I should see ONE bar during that time slot for the day, with the time and the number of jobs for that day in the bar

**Comment by pdpino** [comment]
Do you mean something like this? Plus customizinz the orange box further, according to your needs.

![photo_2021-11-22_12-24-59](https://user-images.githubusercontent.com/20805451/142888790-91a5e3ac-6c89-49db-b888-bdab186356e4.jpg)

You can accomplish this by (1) merging the overlapping events before passing them to the `events` prop, and (2) providing the `EventComponent` prop to show the merged event different than the others.
I can provide a code example to explain this idea further if you need :slightly_smiling_face:

**Comment by rdewolff** [comment]
The problem with this proposition is that it's not possible to visually see the different duration of the event.

**Comment by pdpino** [comment]
> The problem with this proposition is that it's not possible to visually see the different duration of the event.

I agree. I'm trying to understand if that's what @AbhishekMuknak wants for their specific app

**Comment by AbhishekMuknak** [comment]
Yes, I want something like this because there are more events on the same time period the event bars size reduces.

**Comment by AbhishekMuknak** [comment]
Any updates?

**Comment by pdpino** [comment]
As I mentioned, this can already be accomplished with code in your app, something like this:

```js
const events = [
  {
    id: 1,
    description: 'Meeting1',
    color: 'orange',
    startDate: new Date(2021, 11, 15, 12, 0),
    endDate: new Date(2021, 11, 15, 12, 30),
  },
  {
    id: 2,
    description: 'Meeting2',
    color: 'orange',
    startDate: new Date(2021, 11, 15, 12, 0),
    endDate: new Date(2021, 11, 15, 12, 30),
  },
  // ...other non-overlapped events
]

// Merge overlapped events by detecting them in your code
const mergedEvents = [
  {
    id: 1, // unique id
    description: '2 events',
    color: 'orange',
    startDate: new Date(2021, 11, 15, 12, 0),
    endDate: new Date(2021, 11, 15, 12, 30),
    // More fields as needed, for example:
    nOverlapped: 2,
    descriptions: ['Meeting1', 'Meeting2'],
  },
  // ...other non-overlapped events
]

const MyEventComponent = ({ event }) => {
  if (!event.nOverlapped) {
    // default case for non-overlapped events
    return <Text>{event.description}</Text>
  }
  return (
    // ... here you display the overlapped events (with View, Text, etc, as you like)
    // they will be shown inside 1 box (without reducing width)
  )
}

<WeekView
  events={mergedEvents}
  EventComponent={MyEventComponent}
  // ...other props
/>
```

Note: to detect which events are overlapped, one possible method is sorting the events by `startDate` (`O(n log n)`, with `n` events), and then checking them sequentially for overlaps (`O(n)`).

**Comment by pdpino** [comment]
I acknowledge that the solution may seem hacky. In the future we could provide a better way to do this: simpler code in your app, more flexible options, etc.

If you have more suggestions/needs, I'd ask that you provide visual examples to understand better, e.g. an screenshot

**Comment by Salmankhan033** [comment]
Can you send me the sample code, please?

**Comment by pdpino** [comment]
Closing this, see similar discussion in #233

**Comment by rdewolff** [comment]
@pdpino the housekeeper 🥳
