### ISSUE TITLE
I want to disable horizontal and vertical scrolling when dragging an event somehow

### ISSUE THREAD

**Issue by regina-rombangok** [hoangnm/react-native-week-view#154]
Whenever trying to drag the event, calendar view swipe behavior and vertical scrolling behavior work at the same time. It looks like so uncomfortable to drag the event.
Is there any way to disable horizontal and vertical scrolling when dragging the event?
Thanks.

**Comment by pdpino** [comment]
Thanks for trying the drag and drop feature!

We have seen similar issues in some devices. To help u faster, could you please:
* say which device are you using (emulator/physical, android/ios) and packages versions (react, react-native, react-native-week-view)
* ideally provide a screen recording

In some devices it works well, for example android 8.1.0 emulator, react-native v0.64.2, react v17.0.1:
![feature-drag-and-drop-v2-smooth](https://user-images.githubusercontent.com/20805451/144090392-35a255cc-ff06-4fda-a38c-6c02d90600f6.gif)

**Comment by regina-rombangok** [comment]
Thanks for quick reply. I'm testing on Android emulator Pixel 2 device (API 30). 
    "react": "17.0.1",
    "react-native": "0.64.3",
    "react-native-week-view": "^0.7.0"
    
   Here is the video I recorded

https://user-images.githubusercontent.com/71880618/144098212-d2d61849-0922-4a53-b3c6-f0615aa8f8c5.mp4

**Comment by KodyKendall** [comment]
I'm also seeing this when running expo, devise is an iPhone 8 Plus, iOS 15.1

**Comment by pdpino** [comment]
Thanks both for the feedback. I will try disabling other scrollings while the event is being dragged, will let you know how it goes.

I also have been think of providing small feedback when the event is first pressed to be dragged, for example a little phone vibration (like the android calendar does), could be helpful

**Comment by KodyKendall** [comment]
I think adding a little phone vibration is a great idea!

**Comment by KodyKendall** [comment]
@pdpino have you had a chance to experiment with disabling scrollings when an event is being dragged?

**Comment by pdpino** [comment]
@KodyKendall sorry, not yet :slightly_frowning_face:, I have been very busy the last weeks finishing my master thesis.
I will try to make some time for this in 1-2 weeks, but I can't make any promises

**Comment by pdpino** [comment]
Update:

I created [this experimental branch](https://github.com/pdpino/react-native-week-view/tree/experimental/drag-drop-vs-scroll) with 2 changes:

* Use `onShouldBlockNativeResponder: () => false` in the `PanResponder`. This _might_ fix the problem in some cases, though it only applies to android
* Disable the (vertical and horizontal) scrolling when an event is being dragged. Activate this behavior by providing the (experimental) prop `debugLockScrollOnDrag={true}`

I'm still working on providing a small feedback when the dragging starts

@regina-rombangok @KodyKendall I'd appreciate if you could test this, lmk if it improves or not in your devices

**Comment by Spunnator** [comment]
I have same problem. Any Solution?

**Comment by pdpino** [comment]
Hi @Spunnator , could you try the fix I mentioned in my previous comment?

**Comment by Spunnator** [comment]
@pdpino i should use your fork?

**Comment by pdpino** [comment]
Just this branch for testing, if possible.
I keep my fork up to date with this repo

**Comment by pdpino** [comment]
Update: I'm still debugging this

* This bug occurs in really specific cases, due to how `ScrollView`s in react-native work
  * Apparently, can only be fixed with native code
* If you do not provide `onEventPress` neither `onEventLongPress` callbacks, you _should not_ see this problem. (Although probably most use-cases need those callbacks)
* I may try with the [react-native-gesture-handler](https://docs.swmansion.com/react-native-gesture-handler/) library
  * Pros: should be able to fix this problem, maybe even provide feedback when the dragging start
  * Cons: extra library requirement

**Comment by Salmankhan033** [comment]
When I drag the event on midline means half in one date and half of another date then it can't adjust automatically?
Is there any way that it does not drag the event on the midline (date separate line)?

**Comment by pdpino** [comment]
@Salmankhan033 this seems like a question unrelated to this issue (correct me if I'm wrong :sweat_smile:). Could you please open a different issue with the same question? I'll answer there

Also, the current behavior when you drop the event in your example is that will go to March 5 or March 6, depending on the exact pixel where you drop it. What are you expecting? I'm not sure I understand.

**Comment by Salmankhan033** [comment]
let's discuss on #165

**Comment by Salmankhan033** [comment]
I want, when I drag event then off the horizontal scroll and enable vertical scroll?

**Comment by pdpino** [comment]
I fixed this :smile:. I had to add the libraries [react-native-gesture-handler](https://docs.swmansion.com/react-native-gesture-handler/docs/) and [react-native-reanimated](https://docs.swmansion.com/react-native-reanimated/docs/) as dependencies (they work much better than bare react-native APIs). @hoangnm let me know if you agree with this requirement

![feature-v2](https://user-images.githubusercontent.com/20805451/158695121-b84efb55-0910-4fef-b778-0aa4cb6f6d86.gif)

I'll be sending a PR

Note: the event gets the opacity lowered to 0.5 while dragging, but we could customize this in the future (is feasible with the new libs)
