### ISSUE TITLE
In header bar how to name of day on top and below the date like the month name and the year shown in left corner

### ISSUE THREAD

**Issue by AbhishekMuknak** [hoangnm/react-native-week-view#155]

**Comment by pdpino** [comment]
Customize with the prop `formatDateHeader`, e.g. `"ddd DD"` for "Tue 21", "Wed 22", and so on. See all [available formatters](https://momentjs.com/docs/#/displaying/format/) in moment js

I think you can add a breakline by adding `"[\n]"` in between (e.g. `formatDateHeader="ddd[\n]DD"`), though I haven't tested it yet.
