### ISSUE TITLE
Adding backgroundColor property support for grid layout

### ISSUE THREAD

**Issue by mesutaltuncu** [hoangnm/react-native-week-view#157]
Will there be a backgroundColor change feature for the grid in the future?

**Comment by pdpino** [comment]
The grid is currently transparent, so you should be able to change the background color by changing the parent's `backgroundColor` prop:

```js
<View style={{backgroundColor: 'blue'}}>
  <WeekView
    // ...
  />
</View>
```

Lmk if you have any problem or more questions
