### ISSUE TITLE
Adding locale does not work

### ISSUE THREAD

**Issue by SimeonVAtanasov** [hoangnm/react-native-week-view#160]
When passing locale string to the WeekView component there is no change,  but changing the import in WeekView/utils.js to "import moment from 'moment/min/moment-with-locales';" does the job
I'm using expo 43.0.2

**Comment by pdpino** [comment]
Thanks for the report.

What locale are you trying to use? Is it added manually with `addLocale(...)` or not?
I think the issue is related to importing the target locale: https://momentjs.com/docs/#/i18n/loading-into-nodejs/

**Comment by SimeonVAtanasov** [comment]
Thank you for the fast response, adding it manually resolved my case 💯
