### ISSUE TITLE
Numbers of Days issue

### ISSUE THREAD

**Issue by Salmankhan033** [hoangnm/react-native-week-view#162]
when swipe to next or previous then first it takes one-week difference after that it takes the correct date.
number of days are 3
How to solve it?

https://user-images.githubusercontent.com/58082294/152825322-6bf40dc6-1f2c-4507-ae19-622c55b11fb9.mp4

**Comment by pdpino** [comment]
Hi, what version of `react-native-week-view` are you using?

* If you are using an old version, it may have to do with this bug #39 (we are waiting on a fix from react-native)
* If you are using the latest version, could you show the code in your callback for `onSwipeNext` please (and/or `onSwipePrev`). Is it a time-consuming call?

**Comment by Salmankhan033** [comment]
version : "react-native-week-view": "^0.8.1",
 <WeekView
      showTitle={false}
      events={myEvents}
      onSwipeNext={date => props.changeDate(date)}
      onSwipePrev={date => props.changeDate(date)}
      onEventPress={data => props.onBodyClick(data.id)}
      style={styles.body}
      selectedDate={new Date(props.date)}
      onGridClick={() => props.onBodyClick()}

       numberOfDays={props.day}

      numberOfDaysJump={3}
      jumpOnlyOneDay={3}
      headerStyle={styles.header}
      onDragEvent={(event, newStartDate, newEndDate) => {

                       doUpdateEventData(event,newStartDate,newEndDate)

      }
      }
    />
    
    I sent data to the parent component and stored it in the state 
    The function which sets the state value.
      const SelectedDate = text => {
    setDate(new Date(text));
  };
  The component that i called in parent
 <CalendarScreenComponent
          date={date}
          day={1}
          event={eventsDate}
          onBodyClick={navigationHandler}
          changeDate={SelectedDate}
          whenEventChange={whenEventChange}
        />

**Comment by pdpino** [comment]
Could you try not changing the prop `selectedDate` at all? This prop only determines the _initial date shown in the component_, it is not necessary to change it after each swipe.

**Comment by pdpino** [comment]
I see, thanks for providing all these details! Anything else just lmk

I'll try to reproduce it and fix it soon

**Comment by Salmankhan033** [comment]
Thanks dear 
OnSwipePre Problem I solved from the **node_Modules**.

**Comment by Salmankhan033** [comment]
Hi,
Did you find any solution?

**Comment by pdpino** [comment]
I am still not able to fully reproduce this issue. For now, I suggest:

1. Do not change the date in the prop `selectedDate`, since it only sets the _initial date shown_ in the week-view. For example use `selectedDate={new Date()}` or:
  ```js
  const today = new Date(); // outside of render
  // ...
  <WeekView
    selectedDate={today}
    // ...
  />
  ```
2. Try to avoid creating new functions in the render method, for example, instead of:
  ```js
    onSwipeNext={date => props.changeDate(date)}
    onSwipePrev={date => props.changeDate(date)}
    onDragEvent={(event, newStartDate, newEndDate) => {
      doUpdateEventData(event,newStartDate,newEndDate);
    }}
  ```
  use:
  ```js
    onSwipeNext={props.changeDate}
    onSwipePrev={props.changeDate}
    onDragEvent={doUpdateEventData}
  ```


Both 1 and 2 problems may trigger a re-render of the `WeekView` component, which may be causing your problem

**Comment by Salmankhan033** [comment]
I solved my problem.
The problem is that I pass the date state in useEffect dependency when changing the date then call API for that it gives problem.
now I remove it from useEffect and now it's working well.
