### ISSUE TITLE
How can i  disable drag and drop on specific events  ?

### ISSUE THREAD

**Issue by Salmankhan033** [hoangnm/react-native-week-view#166]
I add multiple event with different types, Now I want to disable drag and drops for some events

**Comment by pdpino** [comment]
That cannot be done at the moment.

We can add it, something like passing to each event that should not drag: `disableDrag: true`.

It should be straightforward to implement this

**Comment by Salmankhan033** [comment]
I did it in from node module In Event file line no 308
`onDrag={onDragEvent` && item.data.type != "workingHours" && item.data.type !="timeOff" && this.onDragEvent}`
