### ISSUE TITLE
How to avoid appointment right side space 

### ISSUE THREAD

**Issue by Salmankhan033** [hoangnm/react-native-week-view#167]
There is a space between appointments and Day border, how to remove the space and show appointments on a full day?

 <img src="https://user-images.githubusercontent.com/58082294/157232160-853e8a8a-cf57-4be1-bfdb-52467922838e.png" alt="Drawing"  width="200" height="350"/>

**Comment by pdpino** [comment]
Cannot be done at the moment.

I'm not sure we can provide that, adding a prop sounds like too much for this. Any API proposals?

In the meantime, you can set [this const](https://github.com/hoangnm/react-native-week-view/blob/master/src/Events/Events.js#L23) to 0 (directly in node_modules I mean), haven't tested recently but should work

**Comment by Salmankhan033** [comment]
I did ,change the const `EVENT_HORIZONTAL_PADDING = 15;` to `EVENT_HORIZONTAL_PADDING = 0;` in Events.js file line No:23  in node-modules

**Comment by Salmankhan033** [comment]
> I did ,change the const `EVENT_HORIZONTAL_PADDING = 15;` to `EVENT_HORIZONTAL_PADDING = 0;` in Events.js file line No:23 in node-modules
