### ISSUE TITLE
fixedVertically?

### ISSUE THREAD

**Issue by JoeKlimcak** [hoangnm/react-native-week-view#168]
fixedHorizontally already exists - would it be difficult to implement fixedVertically? This would sort of act as a 'fixed time range', since it's not possible to currently define start/end hour for each day. If using for business (i.e. we only care about business hours), then the whole 24h range just adds a lot of noise & space - would be great if we could restrict to e.g. an 8h range.

Thanks!

**Comment by pdpino** [comment]
Is your use case still business hours? (Or similar?)

I think is better to go with allowing a start-hour and end-hour (similar to #70) instead of disabing the vertical scrolling. Is a more flexible feature.

I'm thinking it should not be so hard to implement.

**Comment by JoeKlimcak** [comment]
Yep, basically just the same N-hour window in a day, and drop the rest.

We are using start/end times - however it is still possible for the user to go beyond those times if they simply scroll, so it doesn't hide the redundant space that's never being used

**Comment by pdpino** [comment]
The props `beginAgendaAt` and `endAgendaAt` allow fixing a range for the week-view, for example between 8am and 5pm

**Comment by JoeKlimcak** [comment]
Well done, @pdpino.
