### ISSUE TITLE
is it possible to change the period of time of the calendar?

### ISSUE THREAD

**Issue by kong2115** [hoangnm/react-native-week-view#177]
Hi, i'm new to the react native.
since the currently calendar are begin in 0:00, how could i change the begin time like 8:00? or any method that i can hide the grid from 0:00 to 8:00?
thank you!

**Comment by pdpino** [comment]
Hi, thanks for trying the library!

You can use the prop `startHour` to indicate the vertical position of the calendar in the first render, for example `startHour={8}` for 8 am. Although the user could still scroll and see the grid between 00:00 and 8:00

Hiding the start of the grid is a feature similar to #168 and #70, like providing `startAt` and `endAt`, and hiding the test of the of the grid.
I'll try to implement this soon

**Comment by pdpino** [comment]
Update: option 2 is now implemented in the props `beginAgendaAt` and `endAgendaAt`
