### ISSUE TITLE
Customize header problem

### ISSUE THREAD

**Issue by ashotosipyan** [hoangnm/react-native-week-view#18]
Please tell me how can I change header's text color and customize the view a little bit. Thanks in advance!

**Comment by pdpino** [comment]
I've seen that there is an undocumented prop `headerStyle` in the `WeekView` component, but is only passed to the container of the header (i.e. you may not be able to change text or other props from components inside the header)

**Comment by hoangnm** [comment]
Hi guys, it's been a long time, I just add the new prop `headerTextColor` to set header's text color.
