### ISSUE TITLE
Selected Date Position.

### ISSUE THREAD

**Issue by Salmankhan033** [hoangnm/react-native-week-view#185]
https://drive.google.com/file/d/1lqqEmuOUd9uyjGTPKPyZ7YgK7XXJ3bvO/view?usp=sharing

when I Select a date from the header and want to show the selected date from the start position, but some dates can't be taken from the start? it may be taken to mid or last.
watch the above video

**Comment by pdpino** [comment]
To be sure, do you mean the following??
- when you press march-25 --> see dates `march-25 | march-26 | march-27`
- when you press march-5 --> see dates `march-5 | march-6 | march-7`
- when you press march-24 --> see dates `march-24 | march-25 | march-26`

This cannot be done at the moment. The days are rendered by pages, in the previous example a page would be march-25-26-27. This would require re-calculating all the pages to show march-24-25-26.

---

This is somewhat related to #128, once we improve that, we may be able to improve this

**Comment by Salmankhan033** [comment]
> 

yes I want to like this

- when you press march-25 --> see dates march-25 | march-26 | march-27
- when you press march-5 --> see dates march-5 | march-6 | march-7
- when you press march-24 --> see dates march-24 | march-25 | march-26
any idea how to do like this.

**Comment by Salmankhan033** [comment]
I clone the new app and checkout to feature/185-gotodate-position but still not working.
It takes the wrong date position.
I want that selected date to show on the left side like as I select 23 then show 23,24,25 etc
24=> 24,24,25
25=>25,26,27
https://user-images.githubusercontent.com/58082294/163953497-e3549af0-7b06-4911-9a4b-1394ee856190.mov

**Comment by pdpino** [comment]
Please provide a minimal code example to reproduce this

**Comment by pdpino** [comment]
* When you press the date in the video, what are the new props provided? (could you show a console log, or something)
* Could the useEffect hook dependecies be wrong? I think it should be `[props.date]` instead of `[props.event]`
  * Could you try setting the hook without dependencies, and see if the issue persists? i.e. `useEffect(() => {...});`

**Comment by Salmankhan033** [comment]
not working

**Comment by pdpino** [comment]
`useEffect` should not return a promise, see here: https://www.robinwieruch.de/react-hooks-fetch-data/

**Comment by SwikarBhattarai** [comment]
I also encountered the same issue. The goToDate function works but the selected date is not moving to first column. Sometimes it goes to last column, sometimes on mid, sometimes on first column. @pdpino 

https://user-images.githubusercontent.com/36293831/183694194-fde75f86-136c-4476-a046-8ef062bd65d0.mp4

.

**Comment by pdpino** [comment]
@SwikarBhattarai this is still not solved. I will try to address it soon

**Comment by SwikarBhattarai** [comment]
@pdpino i think there is some problem when we select date smaller that today's date. When we select date greater that today's date, its working fine. may. be there is some issue in goToIndex function. can you please check that??

**Comment by pdpino** [comment]
@SwikarBhattarai could you provide a screenshot or video showing the problem?

**Comment by SwikarBhattarai** [comment]
https://user-images.githubusercontent.com/36293831/184528271-3f4e3757-ca0a-4b08-913a-988149182b47.mp4

@pdpino check this video

**Comment by pdpino** [comment]
thanks, I'll check this out
