### ISSUE TITLE
goToNextDay & goToPreviousDay

### ISSUE THREAD

**Issue by bosheski** [hoangnm/react-native-week-view#186]
I stumbled accross this library and customized my header with arrow buttons but I have troubles making them work. They should render the next day upon right arrow click and previous day upon left arrow click. Is this done by some of you guys or is there an example as to how I can do it and will the library have such feature in the near future?

**Comment by pdpino** [comment]
* how many days you display? (numberOfDays)
* Have you tried something that didn't work? For example `goToDate()`, `goToNextPage()`
