### ISSUE TITLE
Go to date position 

### ISSUE THREAD

**Issue by Salmankhan033** [hoangnm/react-native-week-view#194]
I clone the new app and checkout to  _`feature/185-gotodate-position`_ but still not working.
It takes the wrong date position.
I want that selected date to show on the left side like as I select 23 then show 23,24,25 etc
24=> 24,24,25
25=>25,26,27
https://user-images.githubusercontent.com/58082294/163953497-e3549af0-7b06-4911-9a4b-1394ee856190.mov

**Comment by pdpino** [comment]
Please provide a minimal code example to help you better
