### ISSUE TITLE
Deprecated usage of `ViewPropTypes` props

### ISSUE THREAD

**Issue by rdewolff** [hoangnm/react-native-week-view#196]
We are trying to use `react-native-week-view` with [react-native-web](https://necolas.github.io/react-native-web) [1] to have as much same code as possible for our web app than for our mobile app at [Meetme](https://www.meetme.io/) [2]. It works great so far! But we have encountered an issue while trying to use this package. It seems there is usage of `ViewPropTypes` in the lib that cause the app to crash on react-native-web. 

The issue is discussed in this [comment](https://github.com/necolas/react-native-web/issues/2110#issuecomment-903267716) [3] for example.

Could we consider updating these usage to ensure the lib is compatible with `react-native-web`? That'd be great for it's usage and perennity 👍 

[1] : https://necolas.github.io/react-native-web - run same code for react-native and web apps
[2]: https://www.meetme.io - 
[3] : https://github.com/necolas/react-native-web/issues/2110#issuecomment-903267716 - comme issue of using deprecated props discussion.

**Comment by rdewolff** [comment]
There is a link with an example on how to fix this [here](https://github.com/wix/react-native-calendars/pull/1424/files)

**Comment by pdpino** [comment]
I think we should be able to do this, seems very straightforward 

Although, after a quick search I think we don't explicitly do `import { ViewPropTypes } from react-native`. I'll check the code further when I can.
It may be useful if you can show an error message or stack trace, to search for the line in our code.

Great to know that it (mostly) works in react-native-web 🚀 (we haven't tested officially)

**Comment by hoangnm** [comment]
hmm, I'm afraid this use case may not work properly with the PR that improves Drag & Drop, @pdpino .

**Comment by pdpino** [comment]
@rdewolff in our code we use `Text.propTypes` ([here](https://github.com/hoangnm/react-native-week-view/blob/master/src/Times/Times.js#L31)), which seems to be deprecated as well (see [RN-0.64 source code](https://github.com/facebook/react-native/blob/0.64-stable/Libraries/Text/Text.js#L251)).
There is no direct usage of `ViewPropTypes`

I think we can replace that by `PropTypes.oneOfType([PropTypes.object, PropTypes.array])`

**Comment by pdpino** [comment]
> I'm afraid this use case may not work properly with the PR that improves Drag & Drop

@hoangnm why not?

AFAIK, react-native-web is supported in [react-native-reanimated](https://docs.swmansion.com/react-native-reanimated/docs/fundamentals/web-support/) and in [react-native-gesture-handler](https://docs.expo.dev/versions/latest/sdk/gesture-handler/) (I have not tested though)
