### ISSUE TITLE
Drag and drop - resize begining or end of the event

### ISSUE THREAD

**Issue by rdewolff** [hoangnm/react-native-week-view#203]
It would be amazing to be able to reszie via drag and drop just the begining or the end of a slot.

Some libs or calendar allow to do this with the following UI:
1. there is a new 'selectedItem' state onLongPress on an event
2. when an item is selected, 2 dots appear on the top edge and bottom edge. 
3. you can drag and drop either the full event, or just the start or the end via the dots

What do you think about this? I'll search for a demo or another lib and record a small video to share here as soon as I found an example of this behavior.

**Comment by rdewolff** [comment]
Using onLongPress to swtch to `selectedItem` mode would allow to fix https://github.com/hoangnm/react-native-week-view/issues/166

**Comment by pdpino** [comment]
Something like the step 3 here: https://github.com/hoangnm/react-native-week-view/issues/58#issuecomment-846487594?

We have a PR implemented already (https://github.com/hoangnm/react-native-week-view/pull/15), but is on hold waiting for the major drag and drop upgrade https://github.com/hoangnm/react-native-week-view/pull/175

**Comment by rdewolff** [comment]
Aaah yes exactly! I searched issues but did not see that one.

**Comment by rdewolff** [comment]
I’ll close this for now. U can mark as duplicate if u need @pdpino
