### ISSUE TITLE
How to re-render component when startHour changes?

### ISSUE THREAD

**Issue by Vidxyz** [hoangnm/react-native-week-view#204]
I'm trying to implement pinch-to-zoom functionality for this component, and I'm trying to do this by making `startHour` and `hoursInDisplay` as state variables to force re-render upon changes, and I've hooked it up to a `PinchGestureHandler` from [react-native-gesture-handler](https://www.npmjs.com/package/react-native-gesture-handler).

However, when the state values are updated, the component does not re-render with the new `startHour`. I've looked at the docs [provided here](https://www.npmjs.com/package/react-native-week-view) and it says `startHour` is `Vertical position of the week-view in the first render (vertically in the agenda).`

Why specifically first render? Can this be made so it can be re-rendered when value changes? Or is there a different way to do this?

I'm looking to translate the zoom event from `react-native-gesture-handler` to then appropriately set the `hoursInDisplay` as well as the `startHour` to ensure the zoom happens at the current `startHour`. Currently, just changing the `hoursInDisplay` causes the hours in display to always start at `00:00`

Here is the relevant code for context

```

const MyComponent = (props) => {

  const DEFAULT_HOURS_TO_DISPLAY = 10;

  const [totalHoursToDisplay, setTotalHoursToDisplay] = useState(10);
  const [startHourTime, setStartHourTime] = useState<number>(10)


  useEffect(() => {
      setStartHourTime(startHourTime)
    }, [totalHoursToDisplay]);

  const pinchGestureCallback = (event) => {
    const hoursToDisplay = Math.max(1, Math.min(10 - Math.round((event.nativeEvent.scale * DEFAULT_HOURS_TO_DISPLAY)), 10))
    setTotalHoursToDisplay(hoursToDisplay)
    
  }

  return (
    <PinchGestureHandler
        onGestureEvent={pinchGestureCallback}
      >
        <View>
          <WeekView
            events={dayEvents}
            selectedDate={startTime}
            isRefreshing={loading}
            RefreshComponent={Loading}
            startHour={startHourTime}
            hoursInDisplay={totalHoursToDisplay}
            ref={viewRef}
            numberOfDays={days}
            onSwipeNext={onDayChange}
            onSwipePrev={onDayChange}
            showNowLine
            TodayHeaderComponent={todayComponent}
            EventComponent={eventComponent}
            formatDateHeader={dateHeaderStr}
            onEventPress={eventPressed}
          />
        </View>
      </PinchGestureHandler>
  );   

}
```

**Comment by rdewolff** [comment]
Oh that would be great to have pinch to zoom hours in display as well as number of days!

**Comment by pdpino** [comment]
> Why specifically first render?

That is the purpose of the prop, just like in a FlatList is the [`initialScrollIndex` prop](https://reactnative.dev/docs/flatlist#initialscrollindex). (We may change the prop name in the future to be more self-explanatory)

We want to support the pinch gesture soon, both vertically (`hoursInDisplay`) and horizontally (`numberOfDays`) (e.g. https://github.com/hoangnm/react-native-week-view/issues/130), but first we need to integrate react-native-gesture-handler (https://github.com/hoangnm/react-native-week-view/pull/175). Hopefully this will be done in the following weeks.

**Comment by pdpino** [comment]
@Vidxyz in the meantime, we could expose a method like `weekViewRef.scrollToHours(hours)`, so that you can call it when the gesture ends. Would this be useful?

**Comment by Vidxyz** [comment]
Follow up question - can we include a listener to retrieve `startTime` or `startHour` when the `WeekView` is scrolled vertically? It seems that there is no scroll listener to the component tracking the current time (at the very top of what's shown in view), and if I wrap the `WeekView` in my own `ScrollView`, then the `startHour` property does not seem to behave as expected

I can create another separate issue for this if that helps

**Comment by pdpino** [comment]
> can we include a listener to retrieve startTime or startHour when the WeekView is scrolled vertically?

Yeah I think we can, something like `onTimeScrolled={(newTime) => { ... }}`.

Can you explain your use case? To understand the context

> wrap the WeekView in my own ScrollView, then the startHour property does not seem to behave as expected

Wrapping the WeekView in a vertical ScrollView (or flatlist) will probably not work, since the WeekView has its own vertical ScrollView (they will conflict)

**Comment by Vidxyz** [comment]
> Can you explain your use case? To understand the context

The use case goes back to my original comment regarding implementing pinch-to-zoom functionality. Since I want the `hoursInDisplay` to be increased/decreased based on pinch gesture, I also want to be able to know what the currently selected time is so that when the `hoursInDisplay` is increased, you are able to "zoom" into the currently selected time (which may have resulted from scrolling the `WeekView` a little before attempting a pinch to zoom into the agenda)

That's why I tried wrapping it in a `ScrollView` to make use of the `onScroll` listener but as you mentioned that breaks other functionality

> Would something like `onTimeScrolled={(newTime) => { ... }}` work? Called when the momentum ends

100% - I think that's exactly what I was hoping for

**Comment by Vidxyz** [comment]
@pdpino seeing as https://github.com/hoangnm/react-native-week-view/pull/205 was merged in, will `onTimeScrolled` be tackled in a separate PR?
