### ISSUE TITLE
How to avoid the extra padding for the event at the right side

### ISSUE THREAD

**Issue by nareshghule-tudip** [hoangnm/react-native-week-view#217]
We have to show the events by merging them. But we are unable to remove the default spacing between the events. Is there any possible way to remove the spacing at the right?

Note: We have forked this library to make it customizable as per our requirements.

<img src="https://user-images.githubusercontent.com/52404174/173369018-1beeb32e-1c37-4f67-9a24-2063aad8bac7.png" width=30% height=30%>

**Comment by pdpino** [comment]
Quick fix: you can set the [constant EVENT_HORIZONTALA_PADDING](https://github.com/hoangnm/react-native-week-view/blob/master/src/Events/Events.js#L23) to 0

Ps: can you describe your other requirements? We'd be interested in hearing more ideas and try supporting them in the future 🙂

**Comment by pdpino** [comment]
> highlight dates i.e, the event start date to end date

Highlight how? Can you provide a visual example?

>  add start and end date to the calendar

Yes! this is feasible. It would also be a good performance improvement (for #209) for users that know the time period in advance.

I'll try to address this soon

**Comment by nareshghule-tudip** [comment]
@pdpino Okay thanks for the update.
Please find the the screenshot to highlight the start date to  end date for the particular event. e.g. If my event is starting from 
7th and ending on 12th so I want to highlight those events. Also need to add the dots based on event count on the particular date. so please let me know on this

<img width="259" alt="Screenshot 2022-06-13 at 10 08 39 PM" src="https://user-images.githubusercontent.com/52404174/173402634-fa99adc9-14a1-4f06-8952-6c5ecba5c057.png">

**Comment by pdpino** [comment]
You can try using the `DayHeaderComponent` to fully customize that

Something roughly like this could work (have not tested though):

```js
const Day = ({ date, formattedDate }) => (
    <View style={flex:1, flexDirection:'column'}}>
        <View style={
            buildBackgroundStyleFor(date, events), // implemented by you
            // e.g. {backgroundColor: 'green', borderRadius: 5}
        }>
            <Text>{formattedDate}</Text>
        </View>
        <Dots events={events} date={date}/> // implemented by you
    </View>
);

<WeekView
    DayHeaderComponent={Day}
    formatDateHeader="dd[\n]D"
    // ...
/>
```

You would have to implement `buildBackgroundStyleFor(date, events)` to determine which days get a special background style, and `<Dots events={events} date={date}/>` to render the dots for the days with 1 or more events.

I notice the solution may not be so elegant. We are welcome to discuss other API ideas if you have any

**Comment by nareshghule-tudip** [comment]
@pdpino Thanks for the help.  I will try to implement this and will let you know if that works or not

**Comment by nareshghule-tudip** [comment]
@pdpino is it possible to merge the events. e.g, lets say if I am having events from 11 Dec to 15 Dec so can we make it as one event. Please find the attached screenshot for the same. 
Thanks in advance.

<img width="297" alt="Screenshot 2022-06-14 at 4 01 22 PM" src="https://user-images.githubusercontent.com/52404174/173557391-3bdcdb20-135a-4793-a620-12c4c9201227.png">

**Comment by pdpino** [comment]
@nareshghule-tudip should be doable, but you'd had to provide the merged events.

I'm thinking we can support "events as blocks", it could be useful in other scenarios as well, like a timetable.

Then provide one event covering the full block. In your example:
```js
events = [{
    startDate: sunday 10th Dec -- 9 am,
    endDate: wednesday 13th Dec -- 11am,
}, {
    startDate: monday 11th Dec -- 11 am,
    endDate: friday 15th Dec -- 1pm,
}]
```
(11am-1pm hours are made up)

Does that make sense? Does it fit with your original data representation?

**Comment by pdpino** [comment]
@nareshghule-tudip is not implemented yet. I will try to implement it soon

**Comment by nareshghule-tudip** [comment]
@pdpino Okay thanks

**Comment by nareshghule-tudip** [comment]
@pdpino Please let me know when it can be ready.

**Comment by nareshghule-tudip** [comment]
@pdpino Can  you please help me to remove the white line between the events. Please refer the screenshot for the same. I have not added any border for the event but still it is showing white line.

![imageedit_1_2347451719](https://user-images.githubusercontent.com/52404174/174133131-0dd833af-ba92-48b1-a18a-659f663938db.png)

**Comment by pdpino** [comment]
@nareshghule-tudip if you are using the gridColumnStyle prop, try setting the color to transparent: `gridColumnStyle={{ borderColor: 'transparent' }}`

If not, please provide the code (and/or main changes in your fork)

**Comment by nareshghule-tudip** [comment]
@pdpino okay thanks will try this if doesn’t  work I will share main changes in our fork

**Comment by pdpino** [comment]
> in some events only it is showing the white line not in every event ... white line is not in some devices but showing in some devices

1. Can you check if the white line is shown only in between _pages_ (i.e. weeks)? in your example should be between Sunday and Monday of the next week (e.g. Sunday 17 and Monday 18)
    * Check this after applying the gridColumnStyle fix

2. Can you provide your code and changes in your fork please.

**Comment by pdpino** [comment]
Closing this question due to inactivity

See #220 for status on feature: block-like events
See #228 for status on feature: customizing events styles

Feel free to re-open if you need help with your specific use-case
