### ISSUE TITLE
Enable click on month and day header

### ISSUE THREAD

**Issue by rdewolff** [hoangnm/react-native-week-view#221]
As a user, I want to be able to click on the month or on the header and have an action happening.

For example, on click on the month I can show a mini calendar to navigate the month quickly.
I can click on the day header, to create a new event at that day, if the calendar is already full of event and the grid is not clickable.

**Comment by pdpino** [comment]
@rdewolff have you tried onDayPress and onMonthPress?

**Comment by rdewolff** [comment]
What? Doh! I did not see these when checking. Sorry about that! Closing!
