### ISSUE TITLE
The event becomes unresponsive if we drag it to the last column

### ISSUE THREAD

**Issue by TheTushar2696** [hoangnm/react-native-week-view#225]
HI ,
The event is becoming unresponsive if we are dragging it to the last column, please find the video attache

https://user-images.githubusercontent.com/40525668/177001075-82415c21-eb3e-480c-add6-992ba54d64cf.mov

d

**Comment by pdpino** [comment]
* What version of react-native-week-view are you using?
* Can you provide your code? Especially your `onDragCallback`

**Comment by TheTushar2696** [comment]
- "react-native-week-view": "0.16.0",
- My code snippet
-
![Screenshot 2022-07-03 at 1 46 15 PM](https://user-images.githubusercontent.com/40525668/177031320-fdd6d346-2b0e-40e5-84fc-86d16199ab65.png)

**Comment by pdpino** [comment]
I think the code needs some fixes. The return value of `myEvents.map()` is lost. Can you try:

```js
const updateEvents = (event, newStartDate, newEndDate) => {
  const newEvents = myEvents.reduce((accumulated, eve) => {
    if (eve.id === event.id) {
      eve.startDate = newStartDate
      eve.endDate = newEndDate
      // (should work, though applying this change immutably would be better)
    }
    accumulated.push(eve)
  }, []);

  setEvents(newEvents) // this is needed
}
```

```diff
<WeekView
  onDragEvent={(event, newStartDate, newEndDate) => 
-    updateEvent(event, newEndDate, newEndDate)
+    updateEvent(event, newStartDate, newEndDate)
  }
/>
```

**Comment by TheTushar2696** [comment]
Hi,
It worked, Thanks
