### ISSUE TITLE
Events: prop type `eventsByDate.2022-07-05[0].ref` is invalid

### ISSUE THREAD

**Issue by gianglt** [hoangnm/react-native-week-view#230]
Thank you for your component.
I have a problem with the given example. The console log shows the following error-warning, which is related  the first event

 ERROR  Warning: Failed prop type: Events: prop type `eventsByDate.2022-07-05[0].ref` is invalid; it must be a function, usually from the `prop-types` package, but received `undefined`.

**Comment by pdpino** [comment]
Can you provide a code snippet? what version of react-native-week-view are you using?
