### ISSUE TITLE
Why the date is wrong?

### ISSUE THREAD

**Issue by magic3584** [hoangnm/react-native-week-view#231]
```` react
const myEvents = [
	{
		id: 1,
		description: '123',
		startDate: new Date(2021, 3, 15, 12, 0),
		endDate: new Date(2021, 3, 15, 12, 30),
		color: 'red'
		// ... more properties if needed,
	},
	{
		id: 1,
		description: '123',
		startDate: new Date(2021, 3, 15, 13, 0),
		endDate: new Date(2021, 3, 15, 13, 30),
		color: 'blue'
		// ... more properties if needed,
	}
	// More events...
]


<WeekView
					events={myEvents}
					selectedDate={new Date(2021, 3, 15)}
					numberOfDays={7}
					locale={'en'}
/>

````

the events should be  on **2021.03.15**,  but they are all on **2021.04.15**. I don't know why.

**Comment by pdpino** [comment]
>  but they are all on 2021.04.15

Do you mean they are appearing on April 15th 2021?
This is expected, the month parameter is the month-index (from 0 to 11), so `monthIndex=3`  is April (per [Date docs](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/Date#syntax))

**Comment by magic3584** [comment]
It's so strange and it's the first time I know.

Thanks, learned it.
