### ISSUE TITLE
Stack event when they can

### ISSUE THREAD

**Issue by rdewolff** [hoangnm/react-native-week-view#233]
What do you think about a more clever way to stack event when they can?

We could overlap events based on the text in it's content.

Check for example how Apple Calendar is doing it:

![Screenshot 2022-07-12 at 16 06 11](https://user-images.githubusercontent.com/130704/178509315-675543e0-4cc1-4588-b2b2-6b2b28215376.png)

What do u think?

**Comment by pdpino** [comment]
Sounds interesting!

Any API suggestions? I'd prefer something more flexible than detecting the same description, to support multiple use cases (e.g. a user may still want them non-stacked, even if they have the same description)

**Comment by pdpino** [comment]
I got this:

![image](https://user-images.githubusercontent.com/20805451/179532590-5c777e6d-5eb4-4a1b-823c-68d71bdc9e0d.png)

I can send a PR after solving open PRs #

**Comment by rdewolff** [comment]
Woaw that's really nice!

**Comment by rdewolff** [comment]
When you stack them, what happens if you put event A at 17h00 and event B at 17h15 ?

**Comment by pdpino** [comment]
![image](https://user-images.githubusercontent.com/20805451/179768847-61f33645-33d5-4985-88d7-7d6c133e87ad.png)

do you mean one of those?

**Comment by rdewolff** [comment]
That seems like a perfect solution. Looking forward testing this!
