### ISSUE TITLE
Issue with the drag sensitivity

### ISSUE THREAD

**Issue by TheTushar2696** [hoangnm/react-native-week-view#234]
I am facing issue in a scenario wherein if have several events covering the entire column and if I scroll horizontally across it, the events are getting dragged which should happen only if I press on the event and drag it deliberately?

Is there a workaround for this that I can patch and make it work?

**Comment by pdpino** [comment]
What version of react-native-week-view are you using?
Could you provide a video/gif showing the problem?

**Comment by TheTushar2696** [comment]
react-native-week-view version : 0.16.0

Sharing a video just to depict the behaviour, this is taken from simulator but also happening in real device, So if we are scrolling and accidentally touch the event the event is dragged 

https://user-images.githubusercontent.com/40525668/178948309-d210202d-8a8e-40f0-af9a-cb63ab259ee3.mov

**Comment by pdpino** [comment]
This should be resolved in version 0.17.0, though we haven't released to npm yet.

Can you try with the code in the master branch? (notice the new [peer dependencies](https://github.com/hoangnm/react-native-week-view#installation)) The drag sensitivity should be much smoother with the new libraries

**Comment by pdpino** [comment]
Yes, the code is already in master.

You can install from github with npm/yarn specifying a branch and commit. You can use the [latest commit](https://github.com/hoangnm/react-native-week-view/commit/9df17df1e1efd8dfa776750d3096445ee0b2d4d8)

**Comment by hoangnm** [comment]
version 0.17.0 was just released to npm, be aware that this has a breaking change.

**Comment by TheTushar2696** [comment]
Hi @hoangnm 
Whats the breaking change? didn't get that

**Comment by hoangnm** [comment]
Hi @TheTushar2696, as mentioned by @pdpino, from the v0.17.0 you have to install two more dependencies to use this library, otherwise it won't work.

**Comment by pdpino** [comment]
@TheTushar2696 can you confirm if this is no longer an issue with v0.17.0 ?

**Comment by TheTushar2696** [comment]
@pdpino 
I still feel that if we are scrolling horizontally, sometimes the events are getting dragged as well

**Comment by pdpino** [comment]
if a user tries to scroll the view horizontally, but places the finger on top of an event, how should the component differentiate if the user wants to scroll or drag the event?

**Comment by TheTushar2696** [comment]
Somehow in Google calendar, it seems like it is able to differentiate it, not sure

**Comment by pdpino** [comment]
I see. In google calendar the user has to press and hold the event to "enable" the drag mode

We could do something like that, but we also want the press-and-hold for editing-mode feature (e.g. a user might want only drag-and-drop, only editing-mode, or both) --> so we need to reconcile the two interactions somehow

**Comment by TheTushar2696** [comment]
@pdpino  Can we have a prop which can help to decide whether the user wants to edit or drag the event on long press, since for people who are using only drag , currently if we are scrolling and accidently touching an event it is getting dragged, so I am suggesting to have drag also on long press, does that makes sense?

**Comment by pdpino** [comment]
@TheTushar2696 I will start working on long-pressing to enable drag

**Comment by TheTushar2696** [comment]
@pdpino  Thanks, In what release can we expect this, 
Thanks in advance

**Comment by TheTushar2696** [comment]
Hi @pdpino

**Comment by TheTushar2696** [comment]
Hi @pdpino ,

Any update on this yet?

**Comment by pdpino** [comment]
Hi @TheTushar2696, it's difficult for us to give an ETA right now since we have multiple features upcoming

Hopefully we'll resolve the PR it in no more than a few weeks. You can keep an eye in the PR discussion for updates :slightly_smiling_face:
