### ISSUE TITLE
Is there a way where we can avoid shrinking of the events occuring at the same time and ovelap it instead?

### ISSUE THREAD

**Issue by TheTushar2696** [hoangnm/react-native-week-view#235]

**Comment by pdpino** [comment]
Something like this? https://github.com/hoangnm/react-native-week-view/issues/233

**Comment by TheTushar2696** [comment]
No, So actually I have blocked some cells in the calendar  as shown in the image by  passing isTimeSlot key in the event, Just as you mentioned in [issue](https://github.com/hoangnm/react-native-week-view/issues/92) 
![2549866c4a0dbadd7d0bf4d1be23907d](https://user-images.githubusercontent.com/40525668/178939598-68f644a9-3555-4db5-9437-84a938a2fff2.png)
,


So I want to enable overlapping of events in the greyed out portion something like this:
![Image from iOS](https://user-images.githubusercontent.com/40525668/178940149-31554f11-a219-4c3d-bd4a-f8126c513011.png)

But actually when I move the event to that greyed out section both the events are getting aligned side by side instead of overlapping

**Comment by pdpino** [comment]
I see

This should be solved by the [upcoming block-like events](https://github.com/hoangnm/react-native-week-view/discussions/220). We are trying to release them soon!

**Comment by TheTushar2696** [comment]
Thanks!

Any ETA on this

**Comment by pdpino** [comment]
There is already a first working version implemented.

But I'm not sure on an ETA for the actual release, since it needs a couple of ongoing refactors (#219 and #229). I'd say still a couple of weeks

**Comment by pdpino** [comment]
Check [this comment](https://github.com/hoangnm/react-native-week-view/issues/92#issuecomment-1440956525) in a similar issue with a solution
