### ISSUE TITLE
BUG: When an event is moved, it doesn't occupy the full cell in the new time - Event should fill space in the cell.

### ISSUE THREAD

**Issue by TheTushar2696** [hoangnm/react-native-week-view#256]
Screen cast for the beaviour:

https://user-images.githubusercontent.com/40525668/186603138-3856eff9-d1b8-41ba-8d5a-6ea741ac0b43.MP4

So here even though we are moving the entire event in a completely empty cell, it is not occupying the entire cell, Is there any workaround for this

**Comment by pdpino** [comment]
Can you show the exact start and end dates of: (1) the moved "Gymnastics" event and (2) the "Seetha" event?

Probably the events are overlapped by 1 or 2 seconds --> they get reduced in width

**Comment by TheTushar2696** [comment]
Hi @pdpino ,
Just logged the start and end dates of events for which its happening:
Event 1:
startDate: Wed Aug 31 2022 04:00:44 GMT+0530,
endDate: Wed Aug 31 2022 05:00:44 GMT+0530,
Event 2:
startDate: Wed Aug 31 2022 05:00:03 GMT+0530,
endDate: Wed Aug 31 2022 06:00:03 GMT+0530,

Please suggest me something here

**Comment by pdpino** [comment]
The events are overlaped by 41 seconds --> they get reduced in width.

@TheTushar2696 for now I suggest this workaround: force your events to have seconds == 0, i.e. they would be at 4:00:00-5:00:00 and at 5:00:00-6:00:00
--> no overlap --> each event will be in a different cell

Let me know if this works for your use case

**Comment by TheTushar2696** [comment]
Hi
Thanks, it did work
