### ISSUE TITLE
BUG: UI Drag

### ISSUE THREAD

**Issue by ChiBao284** [hoangnm/react-native-week-view#258]
**Describe the bug**
Hi. When pagingEnable = {false} the pull fails. Is there any way to fix it?. Thanks

**Visual demo**

https://user-images.githubusercontent.com/53886386/186808680-6ad6c25b-04ae-4ec3-ad03-26f9d0abcc19.mp4

**Environment:**
 - `react-native-week-view`: _e.g. version 0.16.0, master branch_
 - `react-native`: 0.64.2
 - `react`: 17.0.1
 - OS: _e.g. android 9, emulator_

**Comment by pdpino** [comment]
Are you using `pagingEnabled={false}` to scroll a different amount of days at the time? That feature is not supported yet: #128

I will address this soon
