### ISSUE TITLE
How to point to todays date when switching to 1 day view

### ISSUE THREAD

**Issue by TheTushar2696** [hoangnm/react-native-week-view#260]
Currently when I am switching from week view to 1 day view, It is starting from the first date shown in the 7 day view, For example if on the week calendar dates mentioned are from 4 Sept till 11th Sept, when I am switching to day view, It is starting from 4th sept

**Comment by pdpino** [comment]
For now the solution is: call `goToDate(today)` right after changing `numberOfDays`

I think we can improve this in the future by fixing other stuff at the same time (e.g. #128, #185, #186)

**Comment by TheTushar2696** [comment]
Worked, thanks
