### ISSUE TITLE
BUG: adding events creates an error (react-native-gesture-handler)

### ISSUE THREAD

**Issue by Opus26** [hoangnm/react-native-week-view#286]
**Bug description:**
Expo app: the code commented in the example below is responsible for the error displayed in the screenshot. We don't have this error when events is empty, but we are not able to add events to the WeekView.

**Visual demo:**
![image](https://user-images.githubusercontent.com/71282839/205459986-a0d061c4-4105-4530-93d6-8d48e2786896.png)

**Code to reproduce**
```js
// Example:
      <WeekView
        selectedDate={new Date()}
        numberOfDays={7}
        beginAgendaAt={8 * 60}
        endAgendaAt={21 * 60}
        events={
          [
            // {
            //   id: 1,
            //   title: 'Event 1',
            //   startDate: new Date(),
            //   endDate: new Date(),
            //   color: 'red',
            //   eventKind: 'standard',
            //   stackKey: '1',
            //   description: 'Description',
            //   resolveOverlap: 'stack',
            // },
          ] as WeekViewEvent[]
        }
        onDragEvent={(event) => console.log(event)}
        showTitle={false}
        timesColumnWidth={0.13}
        headerStyle={styles.header}
        timeStep={60}
        hoursInDisplay={16}
        showNowLine
        nowLineColor={ColorsType.primary}
        pageStartAt={
          {
            weekday: 0,
          } as PageStartAtOptions
        }
        onGridClick={(date) => console.log(date)}
        DayHeaderComponent={({ date }: { date: any }) => (
          <View style={styles.dayWraper}>
            <Text style={styles.dayComponentDay}>{WEEK[date.format('d')]}</Text>
            <Text style={styles.dayComponentDate}>{date.format('D')}</Text>
          </View>
        )}
      />
```

**Environment:**
 - `react-native-week-view`: "^0.28.0"
 - `react-native-gesture-handler`: "~2.2.1",
 - `@types/react-native`: "^0.69.8",
 - OS: android

**Additional context (optional):**
* Error message: TypeError: _reactNativeGestureHandler.Gesture.Pan().enabled(isDragEnabled).withTestId is not a function. (In '_reactNativeGestureHandler.Gesture.Pan().enabled(isDragEnabled).withTestId("dragGesture-" + event.id)', '_reactNativeGestureHandler.Gesture.Pan().enabled(isDragEnabled).withTestId' is undefined)
* Error located in react-native-week-view > src > Event > Event.js at line 168.

**Comment by hoangnm** [comment]
Hi @Opus26 , the version of `react-native-gesture-handler` should be at least 2.3.0.

**Comment by pdpino** [comment]
I will update the docs with that information
