### ISSUE TITLE
BUG: Issue with block events

### ISSUE THREAD

**Issue by TheTushar2696** [hoangnm/react-native-week-view#291]
**Bug description:**
When using block events, the size of the events only in first column is decreasing, My using case is that on every scroll I am appending an event of block type for a particular time in 7 days of the week as shown in the screen shot, but for the first column events size is decreasing

**Visual demo:**
<img width="205" alt="Screenshot 2022-12-15 at 9 38 24 PM" src="https://user-images.githubusercontent.com/40525668/207911004-2055103f-3cd6-40a6-88c4-52d7af1bd81e.png">
**Code to reproduce**
```js
I am appending the the block event something like:
<WeekView
      events={[getLunchHoursObject(), ...tasks]}
     .... other props
    />


  const getLunchHoursObject = () => {
    return {
      id: '1000',
      description: 'Lunch',
      startDate: getDateForLunchHours(0),
      endDate: getDateForLunchHours(6),
      style: { borderRadius: 0 },
      disableDrag: true,
      disablePress: true,
      color: Colors.calendarLunchHourBlock,
      eventKind: 'block',
    }
  }

```

**Environment:**
 - `react-native-week-view`: 0.28.0
 - `react-native`: 0.66.0
 - `react`: 17
 - OS: iOS

**Additional context (optional):**
* Error message or traceback (if any)
* Steps to reproduce
* ...

**Comment by pdpino** [comment]
I will check this out

* Still happens if you delete the block event?
* Happens on the first render? or only after adding more events on the fly

**Comment by TheTushar2696** [comment]
@pdpino 

So I am adding the block events on the fly, so initially the events are properly rendered but once the block event is added (Lunch hours) the events ui gets distorted

**Comment by pdpino** [comment]
Hi, sorry the late reply.

I was able to reproduce this with the following events:

```js
  {
    id: 1,
    description: 'Event 1',
    startDate: new Date(2023, 1, 21, 10),
    endDate: new Date(2023, 1, 21, 11, 30),
    color: 'blue',
  },
  {
    id: 2,
    description: 'Event 2',
    startDate: new Date(2023, 1, 21, 13),
    endDate: new Date(2023, 1, 21, 14, 30),
    color: 'orange',
  },
  {
    id: 3,
    description: 'Event 3',
    startDate: new Date(2023, 1, 21, 12),
    endDate: new Date(2023, 1, 21, 16),
    color: 'red',
  },
  // If this event is present, Event1 is shrank (should keep maximum width)
  {
    id: 10,
    startDate: new Date(2023, 1, 21, 12, 30),
    endDate: new Date(2023, 1, 25, 17),
    description: '',
    color: 'rgba(0,255,0,0.2)',
    eventKind: 'block',
    style: {
      borderWidth: 0,
    },
  },
```
![reproduce](https://user-images.githubusercontent.com/20805451/220784604-ff4db3a1-a14e-4ce4-883a-630ea20f04db.png)
