### ISSUE TITLE
how can i change the border style of cells ? and how to change the text color of side bar on left that displays hours?

### ISSUE THREAD

**Issue by haseebb** [hoangnm/react-native-week-view#35]

**Comment by hoangnm** [comment]
Currently, these options are not supported by the library, I'll add them to the todo list.

**Comment by pdpino** [comment]
After PR #48 :
* The border style of each event can be customized with the prop `eventContainerStyle`, for example passing: `{ borderWidth: 1, borderColor: 'black' }`. (Is this what you meant by "border style of cells"?)
* The text style of the left bar can be customized with the prop `hourTextStyle`
