### ISSUE TITLE
how to install library 

### ISSUE THREAD

**Issue by nhuthuynh195** [hoangnm/react-native-week-view#4]
how to install library

**Comment by rmariscal13** [comment]
npm install react-native-week-view

i guess for yarn and others has the same structure like
yarn install react-native-week-view

**Comment by hoangnm** [comment]
Thanks @rmariscal13  for your reply. Actually, at the time @nhuthuynh195 asked, I didn't publish it to npm. Now it's available. I should reply sooner. I'm improving this library, thank you for trying it !
