### ISSUE TITLE
Can we make the header and time text views more stylable?

### ISSUE THREAD

**Issue by eiji11** [hoangnm/react-native-week-view#45]
This plugin is great but can we please add additional styles to header texts as well as the time texts at the side? I'm not talking about the containers, just the text itself. Additionally, it might also be good if we can change the class/component of the text view. for example, use another text view component from a UI library.

**Comment by pdpino** [comment]
> This plugin is great but can we please add additional styles to header texts as well as the time texts at the side? I'm not talking about the containers, just the text itself.

Agree! more styles could be passed as props to the components.

> Additionally, it might also be good if we can change the class/component of the text view. for example, use another text view component from a UI library.

Do you mean the text inside each event? This can already be customized with the `EventComponent` prop, there is an [example in the readme](https://github.com/hoangnm/react-native-week-view#custom-eventcomponent)
