### ISSUE TITLE
How do i change the Swipe left and right methods?

### ISSUE THREAD

**Issue by Osher671279** [hoangnm/react-native-week-view#49]
Hey there, 
I would like to change the swipe left and right problems and also i would like to address the issue that its rendering the previous dates and then its rendering the correct dates.

The swipe left and right i want it to fit to how we are usual here in Israel, Swipe left its advance through dates and swipe right its go back to previous dates

I am attaching a video:
[Video](https://vimeo.com/user123931755/review/462057700/18500970d0)

**Comment by hoangnm** [comment]
Hi @Osher671279 , I can't see the video, but I think I understand the issue, it's like `rtl` mode. Let me try to implement it.

**Comment by Osher671279** [comment]
Okay bro in waiting

**Comment by Osher671279** [comment]
> Hi @Osher671279 , I can't see the video, but I think I understand the issue, it's like `rtl` mode. Let me try to implement it.

Hey Bro
Any update? May i kindly ask you to try implement this ASAP? its top priority for my project

**Comment by pdpino** [comment]
Hi @Osher671279 

I think this should not be hard to implement, but it should be done after PR #51 is merged, as it changes some important internal scrolling logic.
I can try to implement this next week :slightly_smiling_face: 

> I am attaching a video:

By the way, I get a video-not-found here :slightly_frowning_face:

**Comment by pdpino** [comment]
@Osher671279 is something like this what you need? (disregarding the flicker)

![rn-week-view-rtl-feature](https://user-images.githubusercontent.com/20805451/95138776-727d1200-0741-11eb-8a19-7c3d782d54a5.gif)

**Comment by pdpino** [comment]
#52 adds this functionality: set the `rightToLeft` prop to `true`

**Comment by Osher671279** [comment]
Wow thanks i wil check this out
