### ISSUE TITLE
Can't navigate/move to date

### ISSUE THREAD

**Issue by pdpino** [hoangnm/react-native-week-view#54]
**Bug:** If the user changes the prop `selectedDate` after the initial render, the component does not move to the new date selected.

**Expected behavior:** the component should move to the selected date as indicated by the `selectedDate` prop.

**Where in the code:**
After [this commit](https://github.com/hoangnm/react-native-week-view/pull/51/commits/45eec8b1f7ce7a3c3fbef44ae14b14ed067d809c) the user can't change the `selectedDate` prop after the initial render (i.e. if the prop changes, the `state.currentMoment` does not get changed).

**Possible solutions:**
1. Provide a method `goToDate()` (or other name), accessible by creating a `ref` to the `WeekView` component. The users would have to connect the ref and use the method, instead of changing the `selectedDate` prop. For example:

```js
import WeekView from 'react-native-week-view';

class MyComponent extends React {
  someMethod = () => {
    const someDate = new Date() // some date...
    this.weekViewRef.goToDate(someDate);
  };

  render() {
    return (
      <WeekView
        ref={(ref) => { this.weekViewRef = ref; }}
        // ...otherProps
      />
    );
  }
}
```

This is similar to the behavior with the `ScrollView`, which provides `scrollTo()` methods.

2. Make `WeekView` a fully controlled component, by removing the `state.currentMoment` and only using the prop `selectedDate` internally. This would mean that the user would **necessarily** have to connect the `onSwipePrev` and `onSwipeNext` methods, to update the prop:

```js
  changeDate = (date) => {
    this.setState({ date });
  };

  render() {
    return (
      <WeekView
        selectedDate={this.state.date}
        onSwipePrev={(date) => this.changeDate(date)}
        onSwipeNext={(date) => this.changeDate(date)}
        // ...otherProps
      />
    );
  }
```

I think the first option is better. I could submit a PR if you agree @hoangnm.
Both are breaking changes.

**Comment by hoangnm** [comment]
Hey @pdpino , many thanks for the suggestions! I removed that code because I thought we rarely need to update the `selectedDate`, but it seems that sometimes we still need it. I agree with you that the first option is better in this case. It's truly awesome if you can raise the PR 🙏 .

**Comment by pdpino** [comment]
Sure! I will send a PR soon

**Comment by hoangnm** [comment]
Great! Thanks!

**Comment by Total-Drive** [comment]
Hi @hoangnm, I am also feeling the same. In the last version I am using the selected date and change my app ruction based on it now I am not able to do that. Can you please add the option.

**Comment by pdpino** [comment]
PR #56 added the `goToDate(date, animated = true)` method, i.e. changing the `selectedDate` prop won't have any effect, but using `goToDate()` should change the date

A note about performance:
* If the user navigates to a date that has already been rendered (i.e. is already contained in the `state.initialDates`), the movement should go very smooth
* If the user navigates to a date that has not been rendered, the animation may seem slow, as new pages have to be added to `state.initialDates`, and then the component moves to the new date.

**Comment by Total-Drive** [comment]
Thanks @pdpino
