### ISSUE TITLE
Can we select time range on the grid?

### ISSUE THREAD

**Issue by KrishnanRanjithkumar** [hoangnm/react-native-week-view#58]
Is it possible to selecting a time range by clicking on the grid and dragging down or up?

**Comment by pdpino** [comment]
This is not implemented for the moment.
For now, there is only the `onGridClick()` prop to receive clicks on the grid

**Comment by KrishnanRanjithkumar** [comment]
Thanks for the reply @pdpino

**Comment by jeminsieow** [comment]
This would be an awesome feature!

**Comment by pdpino** [comment]
We can give this a try!

I have a question, how should it be the visual feedback while the user is dragging? Display a placeholder event? @KrishnanRanjithkumar @jeminsieow do you have any examples?

@hoangnm what do you think about this feature?

**Comment by jeminsieow** [comment]
@pdpino Awesome thank you!
As for the visual feedback, I think Doodle does this really well. The entire time block is movable and has a circle at the bottom, telling users that it is draggable. While dragging, there is a bit of transparency allowing users to see the events underneath it. This then becomes more opaque once the user lets go.

Furthermore, it allows multiple time ranges, which will be really useful as well.

https://user-images.githubusercontent.com/26967037/117703218-15c46700-b1fc-11eb-980e-b6cfd2da37ca.mp4


Google calendar also has great visual feedback, using translucent blocks with a colored outline. Here's an example:

https://user-images.githubusercontent.com/26967037/117704887-f4647a80-b1fd-11eb-8257-8043283d173f.mp4

**Comment by pdpino** [comment]
Nice examples! Thanks!

So the interaction would be: the user makes a first press/long-press, the "new-event" placeholder appears, and allows expanding it down (by dragging the border), and allows moving it through the week-view (by dragging the full component).

* How does the user indicates it is done editing?
* Regarding the first press:
  * If a press is needed, it would conflict with the `onGridClick` callback, i.e. should we call the callback or create the placeholder?
  * If a long-press is needed, it does not conflict with anything

**Comment by KrishnanRanjithkumar** [comment]
Hi @pdpino Thanks!!. I would suggest , It is better to separate adding events and editing events(in this case moving it through the week-view).
So, the event flows for adding events like 
       user long press(on empty grid) -> placeholder appears -> user expands by dragging it -> event ends when the user stops dragging

if the user long presses on the already created event, we can have another callback to allow the event to be moved
The event flows like for editing events 
       user long press (on event) -> some GUI change to let user know the event is selected(like changing the border color and width simply) ->user drags the entire event through week view and drops it where he wants to.

**Comment by pdpino** [comment]
Thanks @KrishnanRanjithkumar for the suggestions! I like the idea of separating the user interactions.

The drag and drop behavior is actually discussed in #14 (we are currently working on a PR to finish that feature)

I will try to implement this feature soon. Any more comments and suggestions are appreciated :slightly_smiling_face:

**Comment by jeminsieow** [comment]
@pdpino Thanks for the response and clarifying! This is what I have in mind:

1. The convention of saving events from Google and Doodle would be a separate button on the screen to save the event.
To follow this convention, perhaps having a callback function that would allow devs to store the placeholder start and end datetimes every time there is a change in the time blocks. (Maybe an array to support multiple selections)
When users are done editing, they can click the save button which the devs can then program to modify the myEvents variable, essentially saving the events using the stored placeholder state.

Essentially, the selector will be just be storing local state of the placeholder start end datetimes, without having the capability to save it. This will then provide the devs freedom to save it however they want (modal, separate screen with other details, etc)

2. Is it possible to have only one of onGridClick or onGridSelect be true? Having both in the component will then throw the dev an error. This will eliminate any conflicts between the 2, and also reduce the presence of hidden features such as tap and hold which users may not grasp instantly.

Would like to know what you think!

**Comment by pdpino** [comment]
I see what you mean, @jeminsieow 

1. Sounds interesting, but I will start trying to implement a simpler behavior, such as the one described by @KrishnanRanjithkumar  in the comments above. From there, we can see if it is appropriate to add more complexity to this library, or if those cases should be handled by each developer in their own app.
2. I agree, `onGridClick` (existing prop) and the upcoming on-grid-drag behavior should be kept separate.

Will keep you updated!

**Comment by AlissonEnz** [comment]
This feature would be awesome! 😄

**Comment by pdpino** [comment]
I'm working on this, and I have a first working version. I separated the user interaction in three steps: creating, moving and editing the bottom of an event. The developer must update the DB externally in each of these interactions

1. The user press (or long press) the empty grid and an event gets created. In this step, I guess you could include a modal or other UI so the user can input title, color and other information for the new event. The developer provides `onGridClick` or `onGridLongPress` callback (the latter is not implemented yet, but we can add it).
2. The user can drag the event around the grid, which changes the day and the hour of the event. This interaction is being developed in PR #72. The developer provides `onDragEvent` callback.
3. The user can long-press an event to enable "editing mode", which allows they to drag the bottom of the event, thus changing the end-hour. When the user stops dragging, the "editing mode" turns off. The developer provides `onEditEventEndDate` callback.

See this video with the full interaction:

https://user-images.githubusercontent.com/20805451/119245243-9dd43600-bb45-11eb-8c4d-e2e7042587cb.mp4

A full implementation of these three interactions would look like this:

```js
class MyComponent extends React.Component {
  state = {
    events: [ /* ... */ ],
  };

  onGridClick = (touchEvt, startHour, date) => {
    // Here you create a new event and update your DB, for example:
    // The startHour is the date and hour pressed by the user:
    const startDate = date;
    startDate.setHours(startHour);

    // The duration is fixed to 2 hours (you could change this value as you want)
    const endDate = new Date(startDate.getTime());
    endDate.setHours(startDate.getHours() + 2);

    // Here you could include a modal or some other UI to receive title, color, duration, etc

    // Update the state
    this.setState({
      events: [
        ...this.state.events,
        {
          id: newId, // you need to set this to a unique ID
          description: 'Some title',
          color: 'blue',
          startDate,
          endDate,
        },
      ],
    });
  };

  onDragEvent = (event, newStartDate, newEndDate) => {
    // Here you should update the event in your DB with the new date and hour
    this.setState({
      events: [
        ...this.state.events.filter(e => e.id !== event.id),
        {
          ...event,
          startDate: newStartDate,
          endDate: newEndDate,
        },
      ],
    });
  };

  onEditEventEndDate = (event, newEndDate) => {
    // Here you update the event in the DB with the newEndDate provided
    this.setState({
      events: [
        ...this.state.events.filter(e => e.id !== event.id),
        {
          ...event,
          endDate: newEndDate,
        },
      ],
    });
  };

  render() {
    return (
      <WeekView
         events={this.state.events}
         onGridClick={this.onGridClick} // Could be onGridLongPress as well
         onDragEvent={this.onDragEvent}
         onEditEventEndDate={this.onEditEventEndDate}
         // ...
      />
  }
}
```

What do you think? @jeminsieow @KrishnanRanjithkumar @AlissonEnz @hoangnm.

---

Some comments:

* Merging steps 1 and 3 in the same touch (i.e. pressing or long-pressing --> creating a placeholder event --> dragging the bottom of the event) is very complicated. When the user first press (or long press), the _empty grid_ is being pressed, but then a _new component_ has to be created, and the touch has to continue as if this _new component_ was being touched in the first place.
* Separating the interaction seems like a better option, the dev can choose which interactions to allow and which to disallow.

**Comment by jeminsieow** [comment]
@pdpino I think that looks great! I agree with separating steps 1 and 3.

In view of the disadvantage you mentioned, I think it would be great if it was possible for the developer to choose the trigger for the "editing mode", to allow either on-event-press or on-event-long-press, instead of just on-event-long-press.

**Comment by pdpino** [comment]
> I think it would be great if it was possible for the developer to choose the trigger for the "editing mode", to allow either on-event-press or on-event-long-press, instead of just on-event-long-press.

Sounds good. Would have to add a prop like `editEventMode="press"|"longPress"`, or something similar

**Comment by jeminsieow** [comment]
Hi @pdpino, is there a branch where we can test this feature?

**Comment by pdpino** [comment]
Sorry @jeminsieow, not yet. I will set up a branch for early testing, hopefully by the end of this week.

For now, you can check [this branch](https://github.com/pdpino/react-native-week-view/tree/feature/drag-and-drop) with the drag-and-drop feature. The new branch will build on top of this one.

**Comment by pdpino** [comment]
@jeminsieow, I pushed this code to a branch in my fork: in [feature/wip/drag-and-create](https://github.com/pdpino/react-native-week-view/tree/feature/wip/drag-and-create). It supports the props `onDragEvent` and `onEditEventEndDate`, like the example provided before. Consider the API completely experimental, and the code is not cleaned yet. Any suggestion or feedback is appreciated!

There is a known issue: the user can edit more than one event at the time (i.e. long-press one event, do not drag the bottom-circle, and long-press another event --> both are in "edit-mode"). This is not intended, I'd say only one event should be editable at the same time.

I will fix this and prepare a PR soon, hopefully in 1-2 weeks.

**Comment by jeminsieow** [comment]
@pdpino Thanks for the update! Currently I'm having some trouble, the "edit mode" doesn't seem to be working for me; Press and hold on event does not go into edit mode. Is the implementation wrong?

Here's the code:
![image](https://user-images.githubusercontent.com/26967037/122059525-4f057d80-ce1f-11eb-92c3-79789be1cb0e.png)

Here's a video:
https://user-images.githubusercontent.com/26967037/122059654-6fcdd300-ce1f-11eb-8662-bdaf27bfc71c.mp4

**Comment by pdpino** [comment]
@jeminsieow sorry, this is a bug.

Try setting the `onEventPress` to something, even to a dummy function if you do not need it, like `onEventPress={() => {}}`.

Since that method is null, the touchable-opacity gets disabled, and the long-press also gets disabled.

I will fix this soon!

**Comment by pdpino** [comment]
@jeminsieow I just pushed to the branch setting `disabled={false}`, so this should not occur anymore (i.e. you should be able to not provide `onEventPress={something}` and be able to long-press the events to edit them)

If this does not work, or anything else comes up, let me know!

**Comment by jeminsieow** [comment]
@pdpino Alright that works now, but there's another issue:

On a physical device, it's impossible to get into the "edit mode" as the drag command will override the tap and hold. (This is because there's definitely going to be some movement when the finger taps on the device, unlike using a mouse and clicking it)

Once I remove the onDragEvent, I am then able to get into edit mode.

**Comment by pdpino** [comment]
@jeminsieow I see. Thanks for the feedback! I haven't actually tested this on a physical device yet.

As a possible solution, I added a check to see if the finger [has moved enough](https://github.com/pdpino/react-native-week-view/blob/feature/wip/drag-and-create/src/Event/Event.js#L14) before enabling the dragging. I choose 2 (pixels), but we may need to choose a different number to work properly. Could you let me know if this works?

**Comment by pdpino** [comment]
Small update: in an effort to split this feature into smaller chunks, I made two small PRs: #110 and #111 with `onGridLongPress` and `onEventLongPress` props to allow more user-interactions

**Comment by rdewolff** [comment]
Editing begining and end of the meeting would be even better :)

**Comment by pdpino** [comment]
First working version:

![rc0-rnwv0 17--2022-06-22 19-17](https://user-images.githubusercontent.com/20805451/175108701-c820da03-0b1f-4d94-b7d6-28778f6993d3.gif)

**Comment by rdewolff** [comment]
Amazing!!
