### ISSUE TITLE
Three-events overlapping issues

### ISSUE THREAD

**Issue by pdpino** [hoangnm/react-native-week-view#59]
**Improvement 1:** When three or more events are overlapped in time, see the current layout (left), and a better arrangement (right) wasting less horizontal space:

![image](https://user-images.githubusercontent.com/20805451/104965191-effd2300-59bc-11eb-8d18-d33517b1ae63.png) | ![image](https://user-images.githubusercontent.com/20805451/104965308-3b173600-59bd-11eb-8aca-5c00689a11e6.png)

---

**Improvement 2:** There is an event-positioning bug when a previous event lasts longer than a following event. The left image is the current behavior, the right image is the desired behavior:

![image](https://user-images.githubusercontent.com/20805451/104965676-fdff7380-59bd-11eb-8005-0bd7da9d76bb.png) |  ![image](https://user-images.githubusercontent.com/20805451/104965890-6e0df980-59be-11eb-9990-ea80fa50b285.png)

---

I have [a commit ready](https://github.com/pdpino/react-native-week-view/commit/f061edf9052e6666b91dea1025ab4ebd699f8856) fixing both these issues, but the PR #56 should be solved before I send a PR, to avoid git conflicts.

**Comment by hoangnm** [comment]
Nice, can't wait to see the MR!
