### ISSUE TITLE
Example is not working

### ISSUE THREAD

**Issue by dentep** [hoangnm/react-native-week-view#64]
Tried your example. The error appears in Header.js Line 21.
![Screenshot 2021-02-07 at 12 08 01](https://user-images.githubusercontent.com/51183188/107141994-2df6c280-693d-11eb-9204-a96ddbd4ae6b.png)

**Comment by pdpino** [comment]
Indeed, `style.color` is undefined, as it comes from the [`styles.header`](https://github.com/hoangnm/react-native-week-view/blob/master/example/App.js#L100) object. But I don't see this error in android with RN 0.62.0 (maybe ios or other RN-version forbid `color` to be undefined?).

@dentep A hotfix for now would be to set any color value in the `styles.header` object mentioned before, like `color: 'white'`.

@hoangnm 
* I think the best solution is to remove the line `{ color: style.color }`, as the text color should be set through the `headerTextStyle` prop and not the `headerStyle` prop (though this would be a breaking change for those using `headerStyle` to set the color).
* Another option is to check if `style.color` is not undefined before accessing it, both in [`Header.js`](https://github.com/hoangnm/react-native-week-view/blob/master/src/Header/Header.js#L24) and [`Title.js`](https://github.com/hoangnm/react-native-week-view/blob/master/src/Title/Title.js#L22)

**Comment by pdpino** [comment]
@hoangnm  I submitted a PR with the first change suggested. Let me know if you prefer a different solution
