### ISSUE TITLE
Is it possible to use the red line at current time like in default diary in iOS? 

### ISSUE THREAD

**Issue by Jack-Alfie** [hoangnm/react-native-week-view#73]
![IMG_AF4F2AAD0744-1](https://user-images.githubusercontent.com/49557103/114379253-31f5c980-9ba6-11eb-94b2-43557af97b7f.jpeg)

I am using your library for my app. It's really great. Now I need to add the red line at the current time in diary. I have attached the screenshot for your reference.  can you able to add that future for me?

**Comment by pdpino** [comment]
Sounds like a nice idea! I could try to implement it.

Question: Should the line update in real-time?

**Comment by pdpino** [comment]
I implemented a "now-line", a red line with a circle to the left.
Set using the prop `showNowLine={true}`, and the `nowLineColor` prop to customize the color (defaults to red).

![image](https://user-images.githubusercontent.com/20805451/114960136-6ed6f000-9e34-11eb-80d1-4508ebd9bf61.png) ![image](https://user-images.githubusercontent.com/20805451/114960161-7c8c7580-9e34-11eb-8b97-04360a98bd25.png)

Notice the line may appear on top of an event:

![image](https://user-images.githubusercontent.com/20805451/114960067-4d760400-9e34-11eb-86d6-0212cdb4ed7c.png)

Implementation detail: The line gets updated every one minute, using a `setInterval` function

**Comment by hoangnm** [comment]
Should the line always be full width, no matter what the `numberOfDays` is set, @pdpino ?

**Comment by Total-Drive** [comment]
@pdpino  Thank you, I really. happy about this feature. I will use this option.

**Comment by hoangnm** [comment]
I see, then I believe we can follow the same display as the android calendar. We can consider the full-width option later.
