### ISSUE TITLE
Is it possible to disable swiping?

### ISSUE THREAD

**Issue by brandonrush99** [hoangnm/react-native-week-view#74]
I'm trying to make a weekly school schedule where I want the Mon-Fri events to be the same. Is there any way to disable swiping? If not, is there an easy way to repeat the events?
*Edit: By swiping i am referring to horizontal swiping. The vertical scroll is fine for me.

**Comment by pdpino** [comment]
There is no way to disable horizontal swiping at the moment. About repeating the events, this library does not provide an easy way to do that; and is also not recommended to repeat the events infinitely, as the component may get slow performance.

I was thinking about implementing a component such as `FixedWeekView` (or other name), to enable showing only one week (without swiping horizontally). Would that work for you?

**Comment by brandonrush99** [comment]
That's pretty much exactly what I am looking for, so that'd be awesome!

**Comment by pdpino** [comment]
I created a `FixedWeekView` component, for now you can test it in [this branch from my fork](https://github.com/pdpino/react-native-week-view/tree/feature/fixed-week), see the docs [here in the readme](https://github.com/pdpino/react-native-week-view/tree/feature/fixed-week#fixedweekview).

Consider the API experimental for now, until is merged to this repo (i.e. the definitive API may change!)

Comments/suggestions/feedback on the usage and documentation are encouraged!

---

Examples using 5 or 7 days:

![image](https://user-images.githubusercontent.com/20805451/114946709-b56b2100-9e19-11eb-887c-7757f15d23a4.png) ![image](https://user-images.githubusercontent.com/20805451/114946668-9c627000-9e19-11eb-838b-781a084429f3.png)

**Comment by brandonrush99** [comment]
Thank you! I'll check it out and let you know how it goes!

**Comment by brandonrush99** [comment]
So I am not sure if maybe I am just doing something wrong, but anytime I put the FixedWeekView inside of a normal View, it breaks the FixedWeekView to where I cannot see the times or scroll. Any advice?

**Comment by pdpino** [comment]
Have you tried the `WeekView` component in that setting (inside of a View)? If `WeekView` works, `FixedWeekView` should work too.

Can you provide a code snippet?

**Comment by pdpino** [comment]
@brandonrush99 I changed the API.

Removed the `FixedWeekView` component to make the code simpler, the same `WeekView` component can be used to display a fixed view. Here a full example:

```js
import WeekView, { createFixedWeekDate } from 'react-native-week-view';

const myEvents = [
  {
    id: 1,
    description: 'Event 1',
    startDate: createFixedWeekDate('Monday', 12), // Day may be passed as string
    endDate: createFixedWeekDate(1, 14), // Or as number, 1 = monday
    color: 'blue',
  },
  {
    id: 2,
    description: 'Event 2',
    startDate: createFixedWeekDate('wed', 16),
    endDate: createFixedWeekDate(3, 16, 30),
    color: 'red',
  },
];

const MyComponent = () => (
  <WeekView
    events={myEvents}
    // Use this prop to disable the horizontal scrolling:
    fixedHorizontally={true}
    // Recommended props:
    showTitle={false} // if true, shows this month and year
    numberOfDays={7} // show from monday to sunday
    formatDateHeader="ddd" // display short name days, e.g. Mon, Tue, etc
    // ... other props
  />
);
```

The code is still in [this branch from my fork](https://github.com/pdpino/react-native-week-view/tree/feature/fixed-week). You can test it from there, or wait on the PR to be merged :slightly_smiling_face:

**Comment by hoangnm** [comment]
The PR for this improvement has been merged.
