### ISSUE TITLE
Need to install moment to run example app

### ISSUE THREAD

**Issue by pdpino** [hoangnm/react-native-week-view#83]
I am not able to run the `example/` app without explicitly adding `moment` as dependency to `example/package.json`. If I don't do this, it throws this error:

```
error: Error: Unable to resolve module `moment` from `node_modules/react-native-week-view/src/utils.js`: moment could not be found within the project or in these directories:
  ../node_modules
```

* Since `react-native-week-view` is added as a link to a parent folder (i.e. in `example/package.json` is listed as `"react-native-week-view": "file:.."`), the `moment` dependency falls into `example/node_modules/react-native-week-view/node_modules/moment` (the nested `node_modules` folder), and not into `example/node_modules/moment`
* When installed normally by any user (not from local), `moment` should get properly installed, and this problem should not occur

@hoangnm are you able to run the app without installing moment directly to `example/`?

I'm using npm v6.14.12 and node v14.16.1, in Ubuntu 16.04. I tested this cloning the repo from master into a new folder.
The whole developing process that I run is the following:

```sh
# 0. Download
git clone https://github.com/hoangnm/react-native-week-view.git
cd react-native-week-view

# 1. Install dependencies:
cd example/
npm install

# 2. Add moment
# With this step, the app runs correctly
# Without this step, it throws the error mentioned
npm install moment

# 3. Install react-native-week-view from local
# 3.1. remove symlink folder, which does not work with the react-native metro-bundler
rm ./node_modules/react-native-week-view
# 3.2. copy using rsync
rsync -v -a ../src ../index.js ../package.json ./node_modules/react-native-week-view/

# 4. run the app
npm run android
npm run start
```

(I'm preparing a PR describing this process)

**Comment by hoangnm** [comment]
Hi @pdpino , I'm checking this issue, and it's working fine from my side without installing `moment` in the example app.

**Comment by pdpino** [comment]
I see, maybe there is an issue in my end. @hoangnm could you provide the npm/yarn version you are using? And the sequence of commands or steps you use to run the app (install, run, etc)?

**Comment by pdpino** [comment]
I used `yarn` instead of `npm` and it works properly.

I think we should only use yarn, and not npm (I was using npm before :sweat_smile:)
