### ISSUE TITLE
Click the button to switch to the new/previous week

### ISSUE THREAD

**Issue by tnghia944** [hoangnm/react-native-week-view#96]
hi all 
instead of scrolling left to right, can i click on the button to do this
<img width="281" alt="Screen Shot 2021-05-15 at 7 32 47 PM" src="https://user-images.githubusercontent.com/53257922/118361184-5df4d800-b5b4-11eb-9fd4-a291a8a3f098.png">
I am currently using goToDate, is that the best way? , when I already know index + 1 / index -1
  const dateTarget = moment(currentMoment).add(isNext ? 1 : -1, 'w')
     this.goToDate(dateTarget);

**Comment by pdpino** [comment]
Hi @tnghia944 Currently, there is no specific way to change pages programatically, other than swiping. As a workaround, you can use `goToDate(date)`, providing a date in the next or prev week.

> ```js
> const dateTarget = moment(currentMoment).add(isNext ? 1 : -1, 'w')
> this.goToDate(dateTarget);
> ```

I think using this code inside the `WeekView.js` would work, though I haven't tested it (and I don't think is the optimum solution).

**Comment by pdpino** [comment]
I'd say we can implement methods to move programatically, something like `goToNextDate()` and `goToPrevDate()`.
What do you think @hoangnm? I think it would be straight-forward by reusing code from `goToDate()`

**Comment by pdpino** [comment]
Ok, I implemented both methods in a PR: `goToNextPage()` and `goToPrevPage()`

@hoangnm let me know what you think!

@tnghia944, for now, you can test this from [this branch in my fork](https://github.com/pdpino/react-native-week-view/tree/feature/go-to-next-page) :slightly_smiling_face:

**Comment by tnghia944** [comment]
hi @pdpino pd
thank you for your support, now when i press next button everything is ok, i can see the calendar scrolll left to right very well, but when i press the prev button the calendar still changes but the not scroll, you can see this?

**Comment by pdpino** [comment]
Yes, I see the same.

This has to do with this old issue: #39. As a summary:
* When the user moves to a date that has not been rendered, a date object has to be added to an array
* If the date is appended (added to the end of the array), everything tends to be smooth (moving to the next page, in this case).
* If the date is prepended (added to the beginning of the array), things may not be so smooth (in this case, the animation for the prev page).

For now, there is no easy way to fix that in this library :slightly_frowning_face:, as this is an issue from react-native `VirtualizedList` (and `FlatList` and `ScrollView`).

**Comment by pdpino** [comment]
A comment about smoothing vs laggy behavior:

* If the primary use case of your app is to go to the past (previous pages), you can set the prop `prependMostRecent={true}`, and things will be smooth to the previous pages (and laggy to the future pages).
* If the primary use case of your app is to go to the future (next pages), you should leave `prependMostRecent={false}` (the default): things will be smooth to the future (and laggy to the past).
* If you need both the past and the future, one of them will be laggy and the other smooth, sadly :slightly_frowning_face: . We hope this can be improved by react-native soon.
